import {
  Controller,
  Get,
  Param,
  HttpException,
  HttpStatus
} from "@nestjs/common";
import * as fs from "fs";
import * as path from "path";

@Controller("projects/:projectId/rtm")
export class RTMController {
  // ---------------------------------------------------------
  // GET FULL RTM (semantic RTM generated by UI pipeline)
  // ---------------------------------------------------------
  @Get()
  getRTM(@Param("projectId") projectId: string) {
    const file = path.join("qlitz-output", projectId, "rtm.json");

    if (!fs.existsSync(file)) {
      throw new HttpException("RTM not found", HttpStatus.NOT_FOUND);
    }

    return JSON.parse(fs.readFileSync(file, "utf8"));
  }
}
