import { FrameworkNode, defineNode } from '../node.model';

export const ARCHITECTURE_NODES: FrameworkNode[] = [

  defineNode({
    id: 'restassured-java-maven',
    label: 'Maven Project',
    category: 'architecture',
    compatibleFrameworks: ['restassured'],
    compatibleLanguages: ['java'],
    templates: ['restassured/java/maven/base'],
    metadata: {
      description: 'Maven project scaffold for REST Assured API testing. Swagger-driven — generates one test class per resource tag. Add test runner, reporting, and data nodes to complete the stack.',
      version: '5.x',
      tags: ['restassured', 'api', 'java', 'maven'],
      docs: 'https://rest-assured.io/',
      since: '1.0.0',
    },
    constraints: {
      required: true,
      maxInstances: 1,
      requires: [],
      conflicts: [],
      recommendedWith: [],
    },
    capabilities: { canBeRoot: true, supportsParallel: true, supportsDistributed: false, hasAIIntegration: false, hasReporting: true, hasRetry: true },
    configSchema: {
      basePackage: { type: 'string', label: 'Base package', default: 'com.qlitz.api', required: true },
    },
  }),

  defineNode({
    id: 'selenium-java-pom',
    label: 'Page Object Model',
    category: 'architecture',
    compatibleFrameworks: ['selenium'],
    compatibleLanguages: ['java'],
    templates: ['selenium/java/pom/base'],
    metadata: {
      description: 'Industry-standard Page Object Model pattern for Selenium + Java. Each page is a class with locators and actions.',
      version: '4.x',
      tags: ['pom', 'oop', 'selenium', 'java', 'design-pattern'],
      docs: 'https://www.selenium.dev/documentation/test_practices/encouraged/page_object_models/',
      since: '1.0.0',
    },
    constraints: {
      required: true,
      maxInstances: 1,
      requires: [],
      conflicts: ['selenium-java-page-factory'],
      recommendedWith: ['selenium-java-testng', 'selenium-java-allure'],
    },
    capabilities: { canBeRoot: true, supportsParallel: true, supportsDistributed: false, hasAIIntegration: false, hasReporting: false, hasRetry: false },
    configSchema: {
      basePackage: { type: 'string', label: 'Base package', default: 'com.qlitz.pages', required: true },
      driverManager: { type: 'enum', label: 'Driver Manager', default: 'webdrivermanager', options: ['webdrivermanager', 'manual'] },
    },
  }),

  defineNode({
    id: 'selenium-java-page-factory',
    label: 'Page Factory',
    category: 'architecture',
    compatibleFrameworks: ['selenium'],
    compatibleLanguages: ['java'],
    templates: ['selenium/java/page-factory/base'],
    metadata: {
      description: 'Selenium Page Factory pattern using @FindBy annotations for element initialization.',
      version: '4.x',
      tags: ['page-factory', 'annotations', 'selenium', 'java'],
      since: '1.0.0',
    },
    constraints: {
      required: true,
      maxInstances: 1,
      requires: [],
      conflicts: ['selenium-java-pom'],
      recommendedWith: ['selenium-java-testng'],
    },
    capabilities: { canBeRoot: true, supportsParallel: false, supportsDistributed: false, hasAIIntegration: false, hasReporting: false, hasRetry: false },
  }),

  defineNode({
    id: 'selenium-python-pom',
    label: 'Page Object Model',
    category: 'architecture',
    compatibleFrameworks: ['selenium'],
    compatibleLanguages: ['python'],
    templates: ['selenium/python/pom/base'],
    metadata: {
      description: 'Page Object Model for Selenium + Python using dataclasses and type hints.',
      version: '4.x',
      tags: ['pom', 'selenium', 'python'],
      since: '1.0.0',
    },
    constraints: { required: true, maxInstances: 1, requires: [], conflicts: [], recommendedWith: ['selenium-python-pytest', 'selenium-python-allure'] },
    capabilities: { canBeRoot: true, supportsParallel: true, supportsDistributed: false, hasAIIntegration: false, hasReporting: false, hasRetry: false },
  }),

  defineNode({
    id: 'playwright-ts-pom',
    label: 'UI Automation (Page Object Model)',
    category: 'architecture',
    compatibleFrameworks: ['playwright'],
    compatibleLanguages: ['typescript', 'javascript'],
    templates: ['playwright/ts/pom/base'],
    metadata: {
      description: 'Playwright UI automation using Page Object Model. Crawls your website URL to generate Page classes, fixtures, and 100% functional test coverage. Supports TypeScript and JavaScript.',
      version: '1.x',
      tags: ['pom', 'playwright', 'typescript', 'javascript', 'ui', 'crawler'],
      docs: 'https://playwright.dev/docs/pom',
      since: '1.0.0',
    },
    constraints: { required: true, maxInstances: 1, requires: [], conflicts: ['playwright-ts-api'], recommendedWith: ['playwright-ts-runner', 'playwright-ts-allure'] },
    capabilities: { canBeRoot: true, supportsParallel: true, supportsDistributed: true, hasAIIntegration: false, hasReporting: false, hasRetry: false },
    configSchema: {
      websiteUrl: { type: 'string', label: 'Website URL to crawl', default: 'https://example.com', required: true },
    },
  }),

  defineNode({
    id: 'playwright-ts-api',
    label: 'API Automation (Swagger-driven)',
    category: 'architecture',
    compatibleFrameworks: ['playwright'],
    compatibleLanguages: ['typescript', 'javascript'],
    templates: ['playwright/ts/api/base'],
    metadata: {
      description: 'Playwright API automation using APIRequestContext. Swagger/OpenAPI-driven — generates one test file per resource tag with 100% positive and negative functional coverage. Supports TypeScript and JavaScript.',
      version: '1.x',
      tags: ['api', 'playwright', 'typescript', 'javascript', 'swagger', 'openapi'],
      docs: 'https://playwright.dev/docs/api-testing',
      since: '1.0.0',
    },
    constraints: { required: true, maxInstances: 1, requires: [], conflicts: ['playwright-ts-pom', 'playwright-ts-hybrid'], recommendedWith: ['playwright-ts-runner', 'playwright-ts-allure'] },
    capabilities: { canBeRoot: true, supportsParallel: true, supportsDistributed: false, hasAIIntegration: false, hasReporting: true, hasRetry: true },
    configSchema: {
      coverageLevel: { type: 'enum', label: 'Coverage level', default: 'functional', options: ['smoke', 'functional'] },
      testDataStrategy: { type: 'enum', label: 'Test data strategy', default: 'faker', options: ['faker', 'csv', 'json'] },
    },
  }),

  defineNode({
    id: 'playwright-ts-hybrid',
    label: 'Hybrid (UI + API)',
    category: 'architecture',
    compatibleFrameworks: ['playwright'],
    compatibleLanguages: ['typescript', 'javascript'],
    templates: ['playwright/ts/hybrid/base'],
    metadata: {
      description: 'Playwright hybrid project combining UI (POM + crawler) and API (Swagger-driven) automation in one codebase. Shared auth fixture, single playwright.config.ts with separate UI and API projects.',
      version: '1.x',
      tags: ['hybrid', 'playwright', 'typescript', 'javascript', 'ui', 'api'],
      docs: 'https://playwright.dev/docs/api-testing',
      since: '1.0.0',
    },
    constraints: { required: true, maxInstances: 1, requires: [], conflicts: ['playwright-ts-pom', 'playwright-ts-api'], recommendedWith: ['playwright-ts-runner', 'playwright-ts-allure'] },
    capabilities: { canBeRoot: true, supportsParallel: true, supportsDistributed: true, hasAIIntegration: false, hasReporting: true, hasRetry: true },
    configSchema: {
      websiteUrl:       { type: 'string', label: 'Website URL to crawl', default: 'https://example.com', required: true },
      coverageLevel:    { type: 'enum',   label: 'Coverage level',       default: 'functional', options: ['smoke', 'functional'] },
      testDataStrategy: { type: 'enum',   label: 'Test data strategy',   default: 'faker',      options: ['faker', 'csv', 'json'] },
    },
  }),

  defineNode({
    id: 'playwright-java-pom',
    label: 'Page Object Model',
    category: 'architecture',
    compatibleFrameworks: ['playwright'],
    compatibleLanguages: ['java'],
    templates: ['playwright/java/pom/base'],
    metadata: {
      description: 'Page Object Model for Playwright + Java using the official playwright-java bindings.',
      version: '1.x',
      tags: ['pom', 'playwright', 'java'],
      since: '1.0.0',
    },
    constraints: { required: true, maxInstances: 1, requires: [], conflicts: [], recommendedWith: ['playwright-java-junit5', 'playwright-java-allure'] },
    capabilities: { canBeRoot: true, supportsParallel: true, supportsDistributed: false, hasAIIntegration: false, hasReporting: false, hasRetry: false },
  }),

  defineNode({
    id: 'playwright-python-pom',
    label: 'Page Object Model',
    category: 'architecture',
    compatibleFrameworks: ['playwright'],
    compatibleLanguages: ['python'],
    templates: ['playwright/python/pom/base'],
    metadata: {
      description: 'Page Object Model for Playwright + Python using pytest fixtures.',
      version: '1.x',
      tags: ['pom', 'playwright', 'python'],
      since: '1.0.0',
    },
    constraints: { required: true, maxInstances: 1, requires: [], conflicts: [], recommendedWith: ['playwright-python-pytest'] },
    capabilities: { canBeRoot: true, supportsParallel: true, supportsDistributed: false, hasAIIntegration: false, hasReporting: false, hasRetry: false },
  }),

  defineNode({
    id: 'playwright-csharp-pom',
    label: 'Page Object Model',
    category: 'architecture',
    compatibleFrameworks: ['playwright'],
    compatibleLanguages: ['csharp'],
    templates: ['playwright/csharp/pom/base'],
    metadata: {
      description: 'Page Object Model for Playwright + C# using Microsoft.Playwright.',
      version: '1.x',
      tags: ['pom', 'playwright', 'csharp'],
      since: '1.0.0',
    },
    constraints: { required: true, maxInstances: 1, requires: [], conflicts: [], recommendedWith: ['playwright-csharp-nunit'] },
    capabilities: { canBeRoot: true, supportsParallel: true, supportsDistributed: false, hasAIIntegration: false, hasReporting: false, hasRetry: false },
  }),

  defineNode({
    id: 'cypress-ts-page-objects',
    label: 'Page Objects',
    category: 'architecture',
    compatibleFrameworks: ['cypress'],
    compatibleLanguages: ['typescript', 'javascript'],
    templates: ['cypress/ts/page-objects/base'],
    metadata: {
      description: 'Page Object pattern for Cypress + TypeScript. Uses custom commands and typed selectors.',
      version: '13.x',
      tags: ['page-objects', 'cypress', 'typescript'],
      docs: 'https://docs.cypress.io/guides/references/best-practices#Page-Objects',
      since: '1.0.0',
    },
    constraints: { required: true, maxInstances: 1, requires: [], conflicts: [], recommendedWith: ['cypress-ts-runner', 'cypress-ts-allure'] },
    capabilities: { canBeRoot: true, supportsParallel: false, supportsDistributed: false, hasAIIntegration: false, hasReporting: false, hasRetry: false },
  }),

  defineNode({
    id: 'webdriverio-ts-page-objects',
    label: 'Page Objects',
    category: 'architecture',
    compatibleFrameworks: ['webdriverio'],
    compatibleLanguages: ['typescript', 'javascript'],
    templates: ['webdriverio/ts/page-objects/base'],
    metadata: {
      description: 'Page Object pattern for WebdriverIO + TypeScript using WDIO page object conventions.',
      version: '8.x',
      tags: ['page-objects', 'webdriverio', 'typescript'],
      since: '1.0.0',
    },
    constraints: { required: true, maxInstances: 1, requires: [], conflicts: [], recommendedWith: ['webdriverio-ts-mocha'] },
    capabilities: { canBeRoot: true, supportsParallel: true, supportsDistributed: false, hasAIIntegration: false, hasReporting: false, hasRetry: false },
  }),

];
