package {{BASE_PACKAGE}}.base;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.WebDriver;

/**
 * Base class for all JUnit 5 Selenium tests.
 * Manages driver lifecycle per test method.
 * @generated by Qlitz Generator
 */
@ExtendWith(ScreenshotOnFailureExtension.class)
public abstract class BaseJUnit5Test {

  protected WebDriver driver;

  @BeforeEach
  public void setUp() {
    driver = DriverFactory.create("{{BROWSER}}", {{HEADLESS}});
    driver.get("{{BASE_URL}}");
  }

  @AfterEach
  public void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }
}
