package {{BASE_PACKAGE}}.base;

import org.junit.jupiter.api.extension.*;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;

import java.io.IOException;
import java.nio.file.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * JUnit 5 extension that captures a screenshot on test failure.
 * @generated by Qlitz Generator
 */
public class ScreenshotOnFailureExtension implements TestWatcher {

  @Override
  public void testFailed(ExtensionContext context, Throwable cause) {
    context.getTestInstance().ifPresent(instance -> {
      if (instance instanceof BaseJUnit5Test test && test.driver instanceof TakesScreenshot ts) {
        byte[] screenshot = ts.getScreenshotAs(OutputType.BYTES);
        String name = context.getDisplayName().replaceAll("[^a-zA-Z0-9]", "_");
        String ts2  = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss"));
        Path dir    = Path.of("target", "screenshots");
        try {
          Files.createDirectories(dir);
          Files.write(dir.resolve(name + "_" + ts2 + ".png"), screenshot);
        } catch (IOException ignored) {}
      }
    });
  }
}
