"""
Allure reporting configuration for {{PROJECT_NAME}}
Add to pytest.ini: addopts = --alluredir=allure-results --clean-alluredir
Framework: {{FRAMEWORK}} | Language: {{LANGUAGE}}
Generated by Qlitz Framework Generator
"""
import allure
import pytest


@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    outcome = yield
    report = outcome.get_result()
    if report.when == "call" and report.failed:
        if hasattr(item, "funcargs"):
            driver = item.funcargs.get("driver")
            if driver:
                allure.attach(
                    driver.get_screenshot_as_png(),
                    name="failure_screenshot",
                    attachment_type=allure.attachment_type.PNG,
                )
