package {{BASE_PACKAGE}}.listeners;

import org.testng.IRetryAnalyzer;
import org.testng.ITestResult;

/**
 * Retries flaky tests up to RETRY_COUNT times.
 * @generated by Qlitz Generator
 */
public class RetryAnalyzer implements IRetryAnalyzer {

  private int attempt = 0;
  private static final int MAX_RETRY = {{RETRY_COUNT}};

  @Override
  public boolean retry(ITestResult result) {
    if (attempt < MAX_RETRY) {
      attempt++;
      return true;
    }
    return false;
  }
}
