package {{BASE_PACKAGE}}.listeners;

import org.testng.IAnnotationTransformer;
import org.testng.annotations.ITestAnnotation;

import java.lang.reflect.Constructor;
import java.lang.reflect.Method;

/**
 * Automatically applies retry count from config to all test methods.
 * @generated by Qlitz Generator
 */
public class RetryListener implements IAnnotationTransformer {

  private static final int RETRY_COUNT = {{RETRY_COUNT}};

  @Override
  public void transform(ITestAnnotation annotation, Class testClass,
                        Constructor testConstructor, Method testMethod) {
    if (annotation.getRetryAnalyzerClass() == null) {
      annotation.setRetryAnalyzer(RetryAnalyzer.class);
    }
  }
}
