import { FrameworkNode, defineNode } from '../node.model';

export const TEST_RUNNER_NODES: FrameworkNode[] = [

  defineNode({
    id: 'selenium-java-testng',
    label: 'TestNG',
    category: 'testRunner',
    compatibleFrameworks: ['selenium'],
    compatibleLanguages: ['java'],
    templates: ['selenium/java/testng/base'],
    metadata: {
      description: 'TestNG test runner for Selenium + Java. Supports parallel execution, data providers, grouping, and retry analyzers.',
      version: '7.x',
      tags: ['testng', 'parallel', 'data-provider', 'groups'],
      docs: 'https://testng.org/doc/',
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: [],
      conflicts: ['selenium-java-junit5'],
      recommendedWith: ['selenium-java-allure', 'selenium-java-retry'],
    },
    capabilities: { canBeRoot: false, supportsParallel: true, supportsDistributed: true, hasAIIntegration: false, hasReporting: false, hasRetry: true },
    configSchema: {
      parallel: { type: 'enum', label: 'Parallel mode', default: 'methods', options: ['methods', 'classes', 'tests', 'none'] },
      threadCount: { type: 'number', label: 'Thread count', default: 4 },
      retryCount: { type: 'number', label: 'Retry count', default: 1 },
    },
  }),

  defineNode({
    id: 'selenium-java-junit5',
    label: 'JUnit 5',
    category: 'testRunner',
    compatibleFrameworks: ['selenium'],
    compatibleLanguages: ['java'],
    templates: ['selenium/java/junit5/base'],
    metadata: {
      description: 'JUnit 5 test runner for Selenium + Java. Modern annotation model with extensions, parameterized tests, and @BeforeEach/@AfterEach lifecycle.',
      version: '5.x',
      tags: ['junit5', 'jupiter', 'parameterized', 'extensions'],
      docs: 'https://junit.org/junit5/',
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: [],
      conflicts: ['selenium-java-testng'],
      recommendedWith: ['selenium-java-allure'],
    },
    capabilities: { canBeRoot: false, supportsParallel: true, supportsDistributed: false, hasAIIntegration: false, hasReporting: false, hasRetry: false },
  }),

  defineNode({
    id: 'playwright-ts-runner',
    label: 'Playwright Test Runner',
    category: 'testRunner',
    compatibleFrameworks: ['playwright'],
    compatibleLanguages: ['typescript', 'javascript'],
    templates: ['playwright/ts/runner/base'],
    metadata: {
      description: 'Playwright\'s built-in test runner. Supports parallel workers, fixtures, retries, and rich reporters natively.',
      version: '1.x',
      tags: ['playwright-test', 'fixtures', 'workers', 'built-in'],
      docs: 'https://playwright.dev/docs/intro',
      since: '1.0.0',
    },
    constraints: {
      required: true,
      maxInstances: 1,
      requires: ['playwright-ts-pom'],
      conflicts: [],
      recommendedWith: ['playwright-ts-allure', 'playwright-ts-sharding'],
    },
    capabilities: { canBeRoot: false, supportsParallel: true, supportsDistributed: true, hasAIIntegration: false, hasReporting: true, hasRetry: true },
    configSchema: {
      workers: { type: 'number', label: 'Workers', default: 4 },
      retries: { type: 'number', label: 'Retries', default: 2 },
      timeout: { type: 'number', label: 'Test timeout (ms)', default: 30000 },
    },
  }),

  defineNode({
    id: 'playwright-java-junit5',
    label: 'JUnit 5',
    category: 'testRunner',
    compatibleFrameworks: ['playwright'],
    compatibleLanguages: ['java'],
    templates: ['playwright/java/junit5/base'],
    metadata: {
      description: 'JUnit 5 integration for Playwright + Java. Uses playwright-java and JUnit Platform Launcher.',
      version: '5.x',
      tags: ['junit5', 'playwright', 'java'],
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: ['playwright-java-pom'],
      conflicts: ['playwright-java-testng'],
      recommendedWith: ['playwright-java-allure'],
    },
    capabilities: { canBeRoot: false, supportsParallel: true, supportsDistributed: false, hasAIIntegration: false, hasReporting: false, hasRetry: false },
  }),

  defineNode({
    id: 'playwright-java-testng',
    label: 'TestNG',
    category: 'testRunner',
    compatibleFrameworks: ['playwright'],
    compatibleLanguages: ['java'],
    templates: ['playwright/java/testng/base'],
    metadata: {
      description: 'TestNG integration for Playwright + Java with parallel execution and data providers.',
      version: '7.x',
      tags: ['testng', 'playwright', 'java', 'parallel'],
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: ['playwright-java-pom'],
      conflicts: ['playwright-java-junit5'],
      recommendedWith: ['playwright-java-allure'],
    },
    capabilities: { canBeRoot: false, supportsParallel: true, supportsDistributed: true, hasAIIntegration: false, hasReporting: false, hasRetry: true },
  }),

  defineNode({
    id: 'playwright-python-pytest',
    label: 'pytest',
    category: 'testRunner',
    compatibleFrameworks: ['playwright'],
    compatibleLanguages: ['python'],
    templates: ['playwright/python/pytest/base'],
    metadata: {
      description: 'pytest integration for Playwright + Python via pytest-playwright plugin. Supports fixtures and parametrize.',
      version: '7.x',
      tags: ['pytest', 'playwright', 'python', 'fixtures'],
      docs: 'https://playwright.dev/python/docs/test-runners',
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: ['playwright-python-pom'],
      conflicts: [],
      recommendedWith: ['playwright-python-allure'],
    },
    capabilities: { canBeRoot: false, supportsParallel: true, supportsDistributed: false, hasAIIntegration: false, hasReporting: false, hasRetry: true },
  }),

  defineNode({
    id: 'playwright-csharp-nunit',
    label: 'NUnit',
    category: 'testRunner',
    compatibleFrameworks: ['playwright'],
    compatibleLanguages: ['csharp'],
    templates: ['playwright/csharp/nunit/base'],
    metadata: {
      description: 'NUnit test framework for Playwright + C# using Microsoft.Playwright.NUnit package.',
      version: '3.x',
      tags: ['nunit', 'playwright', 'csharp'],
      docs: 'https://playwright.dev/dotnet/docs/test-runners',
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: ['playwright-csharp-pom'],
      conflicts: [],
      recommendedWith: [],
    },
    capabilities: { canBeRoot: false, supportsParallel: true, supportsDistributed: false, hasAIIntegration: false, hasReporting: false, hasRetry: false },
  }),

  defineNode({
    id: 'cypress-ts-runner',
    label: 'Cypress Test Runner',
    category: 'testRunner',
    compatibleFrameworks: ['cypress'],
    compatibleLanguages: ['typescript', 'javascript'],
    templates: ['cypress/ts/runner/base'],
    metadata: {
      description: 'Cypress built-in test runner (Mocha + Chai + Sinon). No additional setup required.',
      version: '13.x',
      tags: ['cypress', 'mocha', 'chai', 'built-in'],
      docs: 'https://docs.cypress.io/',
      since: '1.0.0',
    },
    constraints: {
      required: true,
      maxInstances: 1,
      requires: ['cypress-ts-page-objects'],
      conflicts: [],
      recommendedWith: ['cypress-ts-allure'],
    },
    capabilities: { canBeRoot: false, supportsParallel: false, supportsDistributed: false, hasAIIntegration: false, hasReporting: true, hasRetry: true },
  }),

  defineNode({
    id: 'selenium-python-pytest',
    label: 'pytest',
    category: 'testRunner',
    compatibleFrameworks: ['selenium'],
    compatibleLanguages: ['python'],
    templates: ['selenium/python/pytest/base'],
    metadata: {
      description: 'pytest test runner for Selenium + Python. Supports fixtures, parametrize, and a rich plugin ecosystem.',
      version: '7.x',
      tags: ['pytest', 'selenium', 'python', 'fixtures'],
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: ['selenium-python-pom'],
      conflicts: [],
      recommendedWith: ['selenium-python-allure'],
    },
    capabilities: { canBeRoot: false, supportsParallel: true, supportsDistributed: false, hasAIIntegration: false, hasReporting: false, hasRetry: true },
  }),

  defineNode({
    id: 'selenium-csharp-nunit',
    label: 'NUnit',
    category: 'testRunner',
    compatibleFrameworks: ['selenium'],
    compatibleLanguages: ['csharp'],
    templates: ['selenium/csharp/nunit/base'],
    metadata: {
      description: 'NUnit test framework for Selenium + C#.',
      version: '3.x',
      tags: ['nunit', 'selenium', 'csharp'],
      since: '1.0.0',
    },
    constraints: { required: false, maxInstances: 1, requires: [], conflicts: [], recommendedWith: [] },
    capabilities: { canBeRoot: false, supportsParallel: true, supportsDistributed: false, hasAIIntegration: false, hasReporting: false, hasRetry: false },
  }),

  defineNode({
    id: 'webdriverio-ts-mocha',
    label: 'Mocha',
    category: 'testRunner',
    compatibleFrameworks: ['webdriverio'],
    compatibleLanguages: ['typescript', 'javascript'],
    templates: ['webdriverio/ts/mocha/base'],
    metadata: {
      description: 'Mocha test framework for WebdriverIO + TypeScript. Default WDIO runner.',
      version: '10.x',
      tags: ['mocha', 'webdriverio', 'typescript'],
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: ['webdriverio-ts-page-objects'],
      conflicts: ['webdriverio-ts-jasmine'],
      recommendedWith: [],
    },
    capabilities: { canBeRoot: false, supportsParallel: true, supportsDistributed: false, hasAIIntegration: false, hasReporting: false, hasRetry: false },
  }),

  defineNode({
    id: 'webdriverio-ts-jasmine',
    label: 'Jasmine',
    category: 'testRunner',
    compatibleFrameworks: ['webdriverio'],
    compatibleLanguages: ['typescript', 'javascript'],
    templates: ['webdriverio/ts/jasmine/base'],
    metadata: {
      description: 'Jasmine test framework for WebdriverIO + TypeScript.',
      version: '5.x',
      tags: ['jasmine', 'webdriverio', 'typescript'],
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: ['webdriverio-ts-page-objects'],
      conflicts: ['webdriverio-ts-mocha'],
      recommendedWith: [],
    },
    capabilities: { canBeRoot: false, supportsParallel: true, supportsDistributed: false, hasAIIntegration: false, hasReporting: false, hasRetry: false },
  }),

];
