import { Injectable } from '@nestjs/common';
import type { GeneratedFile } from '../templates/template-engine';
import type { FrameworkBlueprint } from '../blueprint/blueprint.model';
import type { SwaggerSummary, ParsedEndpoint } from '../swagger/swagger.types';

@Injectable()
export class PlaywrightJavaApiTestGeneratorService {
  private readonly pkg = 'com.qlitz';

  generate(summary: SwaggerSummary, blueprint: FrameworkBlueprint): GeneratedFile[] {
    const level = blueprint.coverageLevel ?? 'functional';
    const files: GeneratedFile[] = [];
    const byTag = this.groupByTag(summary.endpoints);

    for (const [tag, endpoints] of Object.entries(byTag)) {
      files.push(this.buildTestClass(tag, endpoints, level, summary.baseUrl));
    }

    files.push(this.buildApiBaseTest(summary.baseUrl));
    files.push(this.buildPomXml());
    files.push(this.buildReadme(summary.baseUrl, summary.endpoints.length));

    return files;
  }

  // ─── Test class per tag ───────────────────────────────────────────────────────

  private buildTestClass(tag: string, endpoints: ParsedEndpoint[], level: string, baseUrl: string): GeneratedFile {
    const className = this.toClassName(tag) + 'ApiTest';
    const pkgPath   = this.pkg.replace(/\./g, '/');
    const methods:  string[] = [];

    for (const ep of endpoints) {
      methods.push(...this.buildTestMethods(ep, level));
    }

    return {
      path: `src/test/java/${pkgPath}/api/${className}.java`,
      content: `package ${this.pkg}.api;

import com.microsoft.playwright.*;
import com.microsoft.playwright.options.RequestOptions;
import com.github.javafaker.Faker;
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import java.util.*;

/**
 * Auto-generated API tests — ${tag}
 * Generated by Qlitz Framework Generator
 */
@Tag("api")
class ${className} extends ApiBaseTest {
  private static final Faker faker = new Faker();

${methods.join('\n\n')}
}
`,
    };
  }

  // ─── Test method builders ─────────────────────────────────────────────────────

  private buildTestMethods(ep: ParsedEndpoint, level: string): string[] {
    const tests: string[] = [];
    const ok    = this.expectedStatus(ep);
    const opId  = this.toMethodId(ep.operationId || `${ep.method}_${ep.path}`);
    const path  = this.buildPath(ep, 'faker');
    const body  = this.buildBody(ep, 'faker');

    tests.push(this.buildSmokeMethod(ep, opId, ok, path, body));
    if (level === 'smoke') return tests;

    // Functional positive
    tests.push(this.buildSchemaMethod(ep, opId, ok, path, body));
    tests.push(this.buildResponseTimeMethod(ep, opId, ok, path, body));
    if (ep.method !== 'DELETE') {
      tests.push(this.buildContentTypeMethod(ep, opId, ok, path, body));
    }

    // Functional negative — auth
    if (ep.requiresAuth) {
      tests.push(this.buildNoAuthMethod(ep, opId));
      tests.push(this.buildInvalidTokenMethod(ep, opId));
    }

    // Functional negative — input validation
    if (['POST', 'PUT', 'PATCH'].includes(ep.method)) {
      tests.push(this.buildEmptyBodyMethod(ep, opId));
      tests.push(this.buildMissingFieldMethod(ep, opId));
      tests.push(this.buildInvalidTypeMethod(ep, opId));
      tests.push(this.buildMalformedJsonMethod(ep, opId));
      if (this.hasEnumField(ep)) {
        tests.push(this.buildInvalidEnumMethod(ep, opId));
      }
    }

    // Functional negative — resource
    if (ep.parameters.some(p => p.in === 'path')) {
      tests.push(this.buildNotFoundMethod(ep, opId));
    }
    if (ep.method === 'POST') {
      tests.push(this.buildDuplicateMethod(ep, opId, path, body));
    }

    return tests;
  }

  private buildSmokeMethod(ep: ParsedEndpoint, opId: string, ok: number, path: string, body: string): string {
    const opts = body ? `, RequestOptions.create().setData(${body})` : '';
    return `  @Test
  @Tag("smoke")
  @DisplayName("smoke: ${ep.method} ${ep.path} → ${ok}")
  void smoke_${opId}() {
${body ? `    var payload = ${body};\n` : ''}    var response = request.${ep.method.toLowerCase()}(${path}${body ? `, RequestOptions.create().setData(payload)` : ''});
    assertEquals(${ok}, response.status());
  }`;
  }

  private buildSchemaMethod(ep: ParsedEndpoint, opId: string, ok: number, path: string, body: string): string {
    return `  @Test
  @Tag("functional")
  @DisplayName("functional: ${ep.method} ${ep.path} → response schema valid")
  void functional_${opId}_schemaValid() {
${body ? `    var payload = ${body};\n` : ''}    var response = request.${ep.method.toLowerCase()}(${path}${body ? `, RequestOptions.create().setData(payload)` : ''});
    assertEquals(${ok}, response.status());
    assertFalse(response.text().isBlank(), "Response body should not be empty");
  }`;
  }

  private buildResponseTimeMethod(ep: ParsedEndpoint, opId: string, ok: number, path: string, body: string): string {
    return `  @Test
  @Tag("functional")
  @DisplayName("functional: ${ep.method} ${ep.path} → responds within 5s")
  void functional_${opId}_responseTime() {
${body ? `    var payload = ${body};\n` : ''}    var start    = System.currentTimeMillis();
    var response = request.${ep.method.toLowerCase()}(${path}${body ? `, RequestOptions.create().setData(payload)` : ''});
    var elapsed  = System.currentTimeMillis() - start;
    assertEquals(${ok}, response.status());
    assertTrue(elapsed < 5000, "Response took " + elapsed + "ms — exceeded 5s limit");
  }`;
  }

  private buildContentTypeMethod(ep: ParsedEndpoint, opId: string, ok: number, path: string, body: string): string {
    return `  @Test
  @Tag("functional")
  @DisplayName("functional: ${ep.method} ${ep.path} → content-type application/json")
  void functional_${opId}_contentType() {
${body ? `    var payload = ${body};\n` : ''}    var response = request.${ep.method.toLowerCase()}(${path}${body ? `, RequestOptions.create().setData(payload)` : ''});
    assertEquals(${ok}, response.status());
    var ct = response.headerValue("content-type");
    assertNotNull(ct, "content-type header missing");
    assertTrue(ct.contains("application/json"), "Expected application/json, got: " + ct);
  }`;
  }

  private buildNoAuthMethod(ep: ParsedEndpoint, opId: string): string {
    const literalPath = this.buildPath(ep, 'literal');
    return `  @Test
  @Tag("functional")
  @DisplayName("security: ${ep.method} ${ep.path} → 401 without auth token")
  void security_${opId}_noAuth() {
    var noAuth = playwright.request().newContext(
      new APIRequest.NewContextOptions().setBaseURL(BASE_URL));
    var response = noAuth.${ep.method.toLowerCase()}(${literalPath});
    assertTrue(response.status() == 401 || response.status() == 403,
      "Expected 401/403, got: " + response.status());
    noAuth.dispose();
  }`;
  }

  private buildInvalidTokenMethod(ep: ParsedEndpoint, opId: string): string {
    const literalPath = this.buildPath(ep, 'literal');
    return `  @Test
  @Tag("functional")
  @DisplayName("security: ${ep.method} ${ep.path} → 401 with invalid token")
  void security_${opId}_invalidToken() {
    var response = request.${ep.method.toLowerCase()}(${literalPath},
      RequestOptions.create().setHeader("Authorization", "Bearer invalid-token-xyz"));
    assertTrue(response.status() == 401 || response.status() == 403,
      "Expected 401/403, got: " + response.status());
  }`;
  }

  private buildEmptyBodyMethod(ep: ParsedEndpoint, opId: string): string {
    const literalPath = this.buildPath(ep, 'literal');
    return `  @Test
  @Tag("functional")
  @DisplayName("validation: ${ep.method} ${ep.path} → 400 with empty body")
  void validation_${opId}_emptyBody() {
    var response = request.${ep.method.toLowerCase()}(${literalPath},
      RequestOptions.create().setData(new HashMap<>()));
    assertTrue(response.status() == 400 || response.status() == 422,
      "Expected 400/422, got: " + response.status());
  }`;
  }

  private buildMissingFieldMethod(ep: ParsedEndpoint, opId: string): string {
    const literalPath = this.buildPath(ep, 'literal');
    return `  @Test
  @Tag("functional")
  @DisplayName("validation: ${ep.method} ${ep.path} → 400 with missing required fields")
  void validation_${opId}_missingField() {
    var payload = new HashMap<String, Object>();
    payload.put("__invalid__", true);
    var response = request.${ep.method.toLowerCase()}(${literalPath},
      RequestOptions.create().setData(payload));
    assertTrue(response.status() == 400 || response.status() == 422,
      "Expected 400/422, got: " + response.status());
  }`;
  }

  private buildInvalidTypeMethod(ep: ParsedEndpoint, opId: string): string {
    const literalPath = this.buildPath(ep, 'literal');
    return `  @Test
  @Tag("functional")
  @DisplayName("validation: ${ep.method} ${ep.path} → 400 with invalid field types")
  void validation_${opId}_invalidTypes() {
    var payload = new HashMap<String, Object>();
    payload.put("id", "not-a-number");
    payload.put("name", 12345);
    payload.put("email", false);
    var response = request.${ep.method.toLowerCase()}(${literalPath},
      RequestOptions.create().setData(payload));
    assertTrue(response.status() == 400 || response.status() == 422,
      "Expected 400/422, got: " + response.status());
  }`;
  }

  private buildMalformedJsonMethod(ep: ParsedEndpoint, opId: string): string {
    const literalPath = this.buildPath(ep, 'literal');
    return `  @Test
  @Tag("functional")
  @DisplayName("validation: ${ep.method} ${ep.path} → 400 with malformed JSON")
  void validation_${opId}_malformedJson() {
    var response = playwright.request().newContext(
      new APIRequest.NewContextOptions().setBaseURL(BASE_URL)
        .setExtraHTTPHeaders(Map.of("Content-Type", "application/json", "Authorization", "Bearer " + TOKEN)))
      .${ep.method.toLowerCase()}(${literalPath},
        RequestOptions.create().setData("{malformed-json"));
    assertTrue(response.status() == 400 || response.status() == 415 || response.status() == 422,
      "Expected 400/415/422, got: " + response.status());
  }`;
  }

  private buildInvalidEnumMethod(ep: ParsedEndpoint, opId: string): string {
    const literalPath = this.buildPath(ep, 'literal');
    return `  @Test
  @Tag("functional")
  @DisplayName("validation: ${ep.method} ${ep.path} → 400 with invalid enum value")
  void validation_${opId}_invalidEnum() {
    var payload = new HashMap<String, Object>();
    payload.put("status", "__INVALID_ENUM_VALUE__");
    var response = request.${ep.method.toLowerCase()}(${literalPath},
      RequestOptions.create().setData(payload));
    assertTrue(response.status() == 400 || response.status() == 422,
      "Expected 400/422, got: " + response.status());
  }`;
  }

  private buildNotFoundMethod(ep: ParsedEndpoint, opId: string): string {
    const path = `BASE_URL + "${ep.path.replace(/\{[^}]+\}/g, '999999999')}"`;
    return `  @Test
  @Tag("functional")
  @DisplayName("negative: ${ep.method} ${ep.path} → 404 for non-existent resource")
  void negative_${opId}_notFound() {
    var response = request.${ep.method.toLowerCase()}(${path});
    assertTrue(response.status() == 404 || response.status() == 400,
      "Expected 404/400, got: " + response.status());
  }`;
  }

  private buildDuplicateMethod(ep: ParsedEndpoint, opId: string, path: string, body: string): string {
    return `  @Test
  @Tag("functional")
  @DisplayName("negative: ${ep.method} ${ep.path} → 409 on duplicate create")
  void negative_${opId}_duplicate() {
${body ? `    var payload = ${body};\n` : ''}    request.post(${path}${body ? ', RequestOptions.create().setData(payload)' : ''});
    var response = request.post(${path}${body ? ', RequestOptions.create().setData(payload)' : ''});
    assertTrue(response.status() == 409 || response.status() == 400 || response.status() == 422,
      "Expected 409/400/422, got: " + response.status());
  }`;
  }

  // ─── Shared infrastructure ────────────────────────────────────────────────────

  private buildApiBaseTest(baseUrl: string): GeneratedFile {
    const pkgPath = this.pkg.replace(/\./g, '/');
    return {
      path: `src/test/java/${pkgPath}/api/ApiBaseTest.java`,
      content: `package ${this.pkg}.api;

import com.microsoft.playwright.*;
import org.junit.jupiter.api.*;
import java.util.Map;

public abstract class ApiBaseTest {
  protected static Playwright             playwright;
  protected static APIRequestContext      request;
  protected static final String BASE_URL = System.getenv().getOrDefault("API_BASE_URL", "${baseUrl}");
  protected static final String TOKEN    = System.getenv().getOrDefault("API_TOKEN", "");

  @BeforeAll
  static void setupApi() {
    playwright = Playwright.create();
    request    = playwright.request().newContext(
      new APIRequest.NewContextOptions()
        .setBaseURL(BASE_URL)
        .setExtraHTTPHeaders(Map.of(
          "Authorization",  "Bearer " + TOKEN,
          "Content-Type",   "application/json"
        ))
    );
  }

  @AfterAll
  static void teardownApi() {
    if (request   != null) request.dispose();
    if (playwright != null) playwright.close();
  }
}
`,
    };
  }

  private buildPomXml(): GeneratedFile {
    return {
      path: 'pom.xml',
      content: `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
           http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>${this.pkg}</groupId>
  <artifactId>playwright-api-tests</artifactId>
  <version>1.0.0-SNAPSHOT</version>

  <properties>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <playwright.version>1.44.0</playwright.version>
    <junit.version>5.10.2</junit.version>
    <faker.version>1.0.2</faker.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.microsoft.playwright</groupId>
      <artifactId>playwright</artifactId>
      <version>\${playwright.version}</version>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>\${junit.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.github.javafaker</groupId>
      <artifactId>javafaker</artifactId>
      <version>\${faker.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.2.5</version>
        <configuration>
          <!-- mvn test -Dgroups="smoke & api"  or  mvn test -Dgroups="functional & api" -->
          <groups>\${groups}</groups>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
`,
    };
  }

  private buildReadme(baseUrl: string, endpointCount: number): GeneratedFile {
    return {
      path: 'README.md',
      content: `# Playwright Java API Test Suite

Auto-generated by Qlitz · ${endpointCount} endpoint(s) · Base URL: \`${baseUrl}\`

## Prerequisites
- Java 17+
- Maven 3.9+

## Setup
\`\`\`bash
mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install"
\`\`\`

## Running Tests
\`\`\`bash
# All API tests
mvn test

# Smoke only
mvn test -Dgroups="smoke & api"

# Functional only
mvn test -Dgroups="functional & api"

# Set base URL and token
API_BASE_URL=https://api.your-site.com API_TOKEN=your-token mvn test
\`\`\`

## Project Structure
\`\`\`
src/test/java/com/qlitz/api/
  ApiBaseTest.java          Playwright APIRequestContext lifecycle
  *ApiTest.java             One test class per Swagger tag
\`\`\`
`,
    };
  }

  // ─── Helpers ──────────────────────────────────────────────────────────────────

  private buildPath(ep: ParsedEndpoint, mode: 'faker' | 'literal'): string {
    const withParams = ep.path.replace(/\{[^}]+\}/g, mode === 'faker'
      ? '" + faker.number().numberBetween(1, 1000) + "'
      : '1');
    return `"${withParams}"`;
  }

  private buildBody(ep: ParsedEndpoint, mode: string): string {
    if (!['POST', 'PUT', 'PATCH'].includes(ep.method) || !ep.requestBodySchema) return '';
    const props = ep.requestBodySchema?.properties ?? {};
    const entries = Object.entries(props as Record<string, any>);
    if (!entries.length) return 'new HashMap<>()';

    const lines = entries.map(([key, def]) =>
      `    payload.put("${key}", ${this.javaFake(key, def)});`
    ).join('\n');
    return `buildPayload(faker)`;
  }

  private buildBodyBlock(ep: ParsedEndpoint): string {
    if (!['POST', 'PUT', 'PATCH'].includes(ep.method) || !ep.requestBodySchema) return '';
    const props = ep.requestBodySchema?.properties ?? {};
    const entries = Object.entries(props as Record<string, any>);
    if (!entries.length) return '    var payload = new HashMap<String, Object>();';

    const lines = entries.map(([key, def]) =>
      `    payload.put("${key}", ${this.javaFake(key, def)});`
    ).join('\n');
    return `    var payload = new HashMap<String, Object>();\n${lines}`;
  }

  private javaFake(name: string, def: any): string {
    const n = name.toLowerCase();
    const t = (def?.type ?? 'string').toLowerCase();
    if (n.includes('email'))                           return 'faker.internet().emailAddress()';
    if (n.includes('name') && !n.includes('username')) return 'faker.name().fullName()';
    if (n.includes('username'))                        return 'faker.internet().username()';
    if (n.includes('phone'))                           return 'faker.phoneNumber().phoneNumber()';
    if (n.includes('address') || n.includes('street')) return 'faker.address().streetAddress()';
    if (n.includes('city'))                            return 'faker.address().city()';
    if (n.includes('url') || n.includes('website'))   return 'faker.internet().url()';
    if (n.includes('password'))                        return 'faker.internet().password(12, 16)';
    if (n.includes('date'))                            return 'faker.date().birthday().toString()';
    if (n.includes('title'))                           return 'faker.lorem().words(3)';
    if (n.includes('description'))                     return 'faker.lorem().sentence()';
    if (n.includes('price') || n.includes('amount'))  return 'faker.number().randomDouble(2, 1, 999)';
    if (t === 'integer' || t === 'number')             return 'faker.number().numberBetween(1, 1000)';
    if (t === 'boolean')                               return 'faker.bool().bool()';
    if (t === 'array')                                 return 'List.of()';
    return 'faker.lorem().word()';
  }

  private hasEnumField(ep: ParsedEndpoint): boolean {
    const props = ep.requestBodySchema?.properties;
    if (!props) return false;
    return Object.values(props as Record<string, any>).some((d: any) => d?.enum?.length);
  }

  private expectedStatus(ep: ParsedEndpoint): number {
    const codes = Object.keys(ep.responses).map(Number).filter(n => !isNaN(n)).sort();
    return codes.find(c => c >= 200 && c < 300) ?? 200;
  }

  private groupByTag(endpoints: ParsedEndpoint[]): Record<string, ParsedEndpoint[]> {
    const map: Record<string, ParsedEndpoint[]> = {};
    for (const ep of endpoints) {
      if (!map[ep.tag]) map[ep.tag] = [];
      map[ep.tag].push(ep);
    }
    return map;
  }

  private toClassName(tag: string): string {
    return tag.replace(/[^a-zA-Z0-9\s]/g, ' ').trim()
      .split(/\s+/).map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join('');
  }

  private toMethodId(opId: string): string {
    return opId.replace(/[^a-zA-Z0-9]/g, '_').replace(/_+/g, '_').replace(/^_|_$/g, '');
  }
}
