import { Injectable } from '@nestjs/common';
import type { GeneratedFile } from '../templates/template-engine';
import type { FrameworkBlueprint } from '../blueprint/blueprint.model';
import type { SwaggerSummary, ParsedEndpoint } from '../swagger/swagger.types';

@Injectable()
export class PlaywrightApiTestGeneratorService {

  generate(summary: SwaggerSummary, blueprint: FrameworkBlueprint): GeneratedFile[] {
    const lang       = blueprint.language ?? 'typescript';
    const ext        = lang === 'typescript' ? 'ts' : 'js';
    const level      = blueprint.coverageLevel ?? 'functional';
    const dataStrat  = blueprint.testDataStrategy ?? 'faker';
    const files:     GeneratedFile[] = [];

    const byTag = this.groupByTag(summary.endpoints);

    for (const [tag, endpoints] of Object.entries(byTag)) {
      const fileName = this.toFileName(tag);
      files.push({
        path:    `tests/api/${fileName}.spec.${ext}`,
        content: this.buildSpecFile(tag, endpoints, level, dataStrat, lang, summary.baseUrl),
      });
    }

    // Auth fixture
    files.push(this.buildAuthFixture(ext, summary.baseUrl));

    // Data helpers
    if (dataStrat === 'faker')  files.push(this.buildFakerHelper(ext));
    if (dataStrat === 'csv')    files.push(this.buildCsvHelper(ext));
    if (dataStrat === 'json')   files.push(this.buildJsonHelper(ext));

    // Sample data files
    files.push(this.buildSampleDataFile(dataStrat, summary.endpoints));

    return files;
  }

  // ─── Spec file ────────────────────────────────────────────────────────────────

  private buildSpecFile(
    tag:       string,
    endpoints: ParsedEndpoint[],
    level:     string,
    dataStrat: string,
    lang:      string,
    baseUrl:   string,
  ): string {
    const isTs      = lang === 'typescript';
    const dataImport = this.buildDataImport(dataStrat, isTs);
    const tests      = endpoints.flatMap(ep => this.buildTests(ep, level, dataStrat, isTs));

    return `import { test, expect } from '@playwright/test';
${dataImport}

/**
 * Auto-generated API tests — ${tag}
 * Coverage: ${level} | Data: ${dataStrat}
 * Generated by Qlitz Framework Generator
 */
test.describe('${tag} API', () => {
${tests.join('\n\n')}
});
`;
  }

  private buildDataImport(dataStrat: string, isTs: boolean): string {
    if (dataStrat === 'faker') return `import { faker } from '@faker-js/faker';`;
    if (dataStrat === 'csv')   return `import { loadCsv } from '../helpers/csv-helper';`;
    if (dataStrat === 'json')  return `import { loadJson } from '../helpers/json-helper';`;
    return '';
  }

  // ─── Test builders ────────────────────────────────────────────────────────────

  private buildTests(ep: ParsedEndpoint, level: string, dataStrat: string, isTs: boolean): string[] {
    const tests:  string[] = [];
    const opId    = this.toMethodName(ep.operationId);
    const ok      = this.expectedStatus(ep);
    const pathFn  = this.buildPathFn(ep, dataStrat);
    const bodyFn  = this.buildBodyFn(ep, dataStrat);
    const qFn     = this.buildQueryFn(ep, dataStrat);

    // ── Smoke: happy path ──────────────────────────────────────────────────────
    tests.push(this.buildSmokeTest(ep, opId, ok, pathFn, bodyFn, qFn, dataStrat));

    if (level !== 'functional') return tests;

    // ── Functional positive ────────────────────────────────────────────────────
    tests.push(this.buildSchemaTest(ep, opId, ok, pathFn, bodyFn, qFn, dataStrat));
    tests.push(this.buildResponseTimeTest(ep, opId, ok, pathFn, bodyFn, qFn, dataStrat));
    if (ep.method !== 'DELETE') {
      tests.push(this.buildContentTypeTest(ep, opId, ok, pathFn, bodyFn, qFn, dataStrat));
    }

    // ── Functional negative — auth ─────────────────────────────────────────────
    if (ep.requiresAuth) {
      tests.push(this.buildNoAuthTest(ep, opId));
      tests.push(this.buildInvalidTokenTest(ep, opId));
    }

    // ── Functional negative — input validation ─────────────────────────────────
    if (['POST', 'PUT', 'PATCH'].includes(ep.method)) {
      tests.push(this.buildEmptyBodyTest(ep, opId));
      tests.push(this.buildMissingRequiredFieldTest(ep, opId));
      tests.push(this.buildInvalidTypeTest(ep, opId));
      tests.push(this.buildMalformedJsonTest(ep, opId));
      if (this.hasEnumField(ep)) {
        tests.push(this.buildInvalidEnumTest(ep, opId));
      }
    }

    // ── Functional negative — resource ─────────────────────────────────────────
    if (ep.parameters.some(p => p.in === 'path')) {
      tests.push(this.buildNotFoundTest(ep, opId));
    }
    if (ep.method === 'POST') {
      tests.push(this.buildDuplicateTest(ep, opId, pathFn, bodyFn, dataStrat));
    }

    return tests;
  }

  // ── Positive tests ──────────────────────────────────────────────────────────

  private buildSmokeTest(ep: ParsedEndpoint, opId: string, ok: number, pathFn: string, bodyFn: string, qFn: string, dataStrat: string): string {
    const dataLine = this.buildDataLine(dataStrat, ep);
    return `  test('smoke: ${ep.method} ${ep.path} → ${ok}', async ({ request }) => {
${dataLine}    const response = await request.${this.reqMethod(ep)}(\`${pathFn}\`${this.reqOptions(ep, bodyFn, qFn)});
    expect(response.status()).toBe(${ok});
  });`;
  }

  private buildSchemaTest(ep: ParsedEndpoint, opId: string, ok: number, pathFn: string, bodyFn: string, qFn: string, dataStrat: string): string {
    const dataLine = this.buildDataLine(dataStrat, ep);
    return `  test('functional: ${ep.method} ${ep.path} → response schema valid', async ({ request }) => {
${dataLine}    const response = await request.${this.reqMethod(ep)}(\`${pathFn}\`${this.reqOptions(ep, bodyFn, qFn)});
    expect(response.status()).toBe(${ok});
    const body = await response.json().catch(() => null);
    expect(body).not.toBeNull();
  });`;
  }

  private buildResponseTimeTest(ep: ParsedEndpoint, opId: string, ok: number, pathFn: string, bodyFn: string, qFn: string, dataStrat: string): string {
    const dataLine = this.buildDataLine(dataStrat, ep);
    return `  test('functional: ${ep.method} ${ep.path} → responds within 5s', async ({ request }) => {
${dataLine}    const start    = Date.now();
    const response = await request.${this.reqMethod(ep)}(\`${pathFn}\`${this.reqOptions(ep, bodyFn, qFn)});
    const elapsed  = Date.now() - start;
    expect(response.status()).toBe(${ok});
    expect(elapsed).toBeLessThan(5000);
  });`;
  }

  private buildContentTypeTest(ep: ParsedEndpoint, opId: string, ok: number, pathFn: string, bodyFn: string, qFn: string, dataStrat: string): string {
    const dataLine = this.buildDataLine(dataStrat, ep);
    return `  test('functional: ${ep.method} ${ep.path} → content-type application/json', async ({ request }) => {
${dataLine}    const response = await request.${this.reqMethod(ep)}(\`${pathFn}\`${this.reqOptions(ep, bodyFn, qFn)});
    expect(response.status()).toBe(${ok});
    expect(response.headers()['content-type']).toContain('application/json');
  });`;
  }

  // ── Negative — auth ──────────────────────────────────────────────────────────

  private buildNoAuthTest(ep: ParsedEndpoint, opId: string): string {
    const path = this.buildLiteralPath(ep);
    return `  test('security: ${ep.method} ${ep.path} → 401 without auth token', async ({ request }) => {
    const response = await request.${this.reqMethod(ep)}(\`${path}\`, {
      headers: { 'Content-Type': 'application/json' },
    });
    expect([401, 403]).toContain(response.status());
  });`;
  }

  private buildInvalidTokenTest(ep: ParsedEndpoint, opId: string): string {
    const path = this.buildLiteralPath(ep);
    return `  test('security: ${ep.method} ${ep.path} → 401 with invalid token', async ({ request }) => {
    const response = await request.${this.reqMethod(ep)}(\`${path}\`, {
      headers: { 'Authorization': 'Bearer invalid-token-xyz', 'Content-Type': 'application/json' },
    });
    expect([401, 403]).toContain(response.status());
  });`;
  }

  // ── Negative — input validation ──────────────────────────────────────────────

  private buildEmptyBodyTest(ep: ParsedEndpoint, opId: string): string {
    const path = this.buildLiteralPath(ep);
    return `  test('validation: ${ep.method} ${ep.path} → 400 with empty body', async ({ request }) => {
    const response = await request.${this.reqMethod(ep)}(\`${path}\`, {
      data: {},
    });
    expect([400, 422]).toContain(response.status());
  });`;
  }

  private buildMissingRequiredFieldTest(ep: ParsedEndpoint, opId: string): string {
    const path = this.buildLiteralPath(ep);
    return `  test('validation: ${ep.method} ${ep.path} → 400 with missing required fields', async ({ request }) => {
    const response = await request.${this.reqMethod(ep)}(\`${path}\`, {
      data: { __invalid__: true },
    });
    expect([400, 422]).toContain(response.status());
  });`;
  }

  private buildInvalidTypeTest(ep: ParsedEndpoint, opId: string): string {
    const path = this.buildLiteralPath(ep);
    return `  test('validation: ${ep.method} ${ep.path} → 400 with invalid field types', async ({ request }) => {
    const response = await request.${this.reqMethod(ep)}(\`${path}\`, {
      data: { id: 'not-a-number', name: 12345, email: false },
    });
    expect([400, 422]).toContain(response.status());
  });`;
  }

  private buildMalformedJsonTest(ep: ParsedEndpoint, opId: string): string {
    const path = this.buildLiteralPath(ep);
    return `  test('validation: ${ep.method} ${ep.path} → 400 with malformed JSON', async ({ request }) => {
    const response = await request.fetch(\`${path}\`, {
      method: '${ep.method}',
      body:    '{malformed-json',
      headers: { 'Content-Type': 'application/json' },
    });
    expect([400, 415, 422]).toContain(response.status());
  });`;
  }

  private buildInvalidEnumTest(ep: ParsedEndpoint, opId: string): string {
    const path = this.buildLiteralPath(ep);
    return `  test('validation: ${ep.method} ${ep.path} → 400 with invalid enum value', async ({ request }) => {
    const response = await request.${this.reqMethod(ep)}(\`${path}\`, {
      data: { status: '__INVALID_ENUM_VALUE__' },
    });
    expect([400, 422]).toContain(response.status());
  });`;
  }

  // ── Negative — resource ──────────────────────────────────────────────────────

  private buildNotFoundTest(ep: ParsedEndpoint, opId: string): string {
    const path = ep.path.replace(/\{[^}]+\}/g, '999999999');
    return `  test('negative: ${ep.method} ${ep.path} → 404 for non-existent resource', async ({ request }) => {
    const response = await request.${this.reqMethod(ep)}(\`\${baseURL}${path}\`);
    expect([404, 400]).toContain(response.status());
  });`;
  }

  private buildDuplicateTest(ep: ParsedEndpoint, opId: string, pathFn: string, bodyFn: string, dataStrat: string): string {
    const dataLine = this.buildDataLine(dataStrat, ep);
    return `  test('negative: ${ep.method} ${ep.path} → 409 on duplicate create', async ({ request }) => {
${dataLine}    await request.post(\`${pathFn}\`${this.reqOptions(ep, bodyFn, '')});
    const response = await request.post(\`${pathFn}\`${this.reqOptions(ep, bodyFn, '')});
    expect([409, 400, 422]).toContain(response.status());
  });`;
  }

  // ─── Data helpers ─────────────────────────────────────────────────────────────

  private buildDataLine(dataStrat: string, ep: ParsedEndpoint): string {
    if (dataStrat === 'faker') return '';
    if (dataStrat === 'csv') {
      return `    const rows = loadCsv('testdata/${this.toFileName(ep.tag)}_data.csv');\n    const data = rows[0] ?? {};\n`;
    }
    if (dataStrat === 'json') {
      return `    const data = loadJson('testdata/${this.toFileName(ep.tag)}_data.json')[0] ?? {};\n`;
    }
    return '';
  }

  private buildPathFn(ep: ParsedEndpoint, dataStrat: string): string {
    return ep.path.replace(/\{([^}]+)\}/g, (_, name) => {
      if (dataStrat === 'faker') return `\${faker.number.int({ min: 1, max: 1000 })}`;
      if (dataStrat === 'csv' || dataStrat === 'json') return `\${data['${name}'] ?? '1'}`;
      return '1';
    });
  }

  private buildLiteralPath(ep: ParsedEndpoint): string {
    return `\${baseURL}` + ep.path.replace(/\{[^}]+\}/g, '1');
  }

  private buildBodyFn(ep: ParsedEndpoint, dataStrat: string): string {
    if (!['POST', 'PUT', 'PATCH'].includes(ep.method) || !ep.requestBodySchema) return '';
    const schema = ep.requestBodySchema;
    const props  = schema?.properties ?? {};
    const body: Record<string, string> = {};

    for (const [key, def] of Object.entries(props as Record<string, any>)) {
      if (dataStrat === 'csv' || dataStrat === 'json') {
        body[key] = `data['${key}'] ?? ''`;
      } else {
        body[key] = this.fakerValueForField(key, def);
      }
    }

    if (!Object.keys(body).length) {
      return dataStrat === 'faker' ? '{}' : 'data';
    }

    if (dataStrat === 'csv' || dataStrat === 'json') return 'data';

    const entries = Object.entries(body).map(([k, v]) => `      ${k}: ${v}`).join(',\n');
    return `{\n${entries}\n    }`;
  }

  private buildQueryFn(ep: ParsedEndpoint, dataStrat: string): string {
    const qParams = ep.parameters.filter(p => p.in === 'query' && p.required);
    if (!qParams.length) return '';
    const parts = qParams.map(p => {
      const val = p.enum?.length
        ? `'${p.enum[0]}'`
        : dataStrat === 'faker'
          ? this.fakerValueForField(p.name, { type: p.type })
          : `data['${p.name}'] ?? ''`;
      return `      ${p.name}: ${val}`;
    }).join(',\n');
    return `{\n${parts}\n    }`;
  }

  private reqMethod(ep: ParsedEndpoint): string {
    return ep.method.toLowerCase();
  }

  private reqOptions(ep: ParsedEndpoint, bodyFn: string, qFn: string): string {
    const parts: string[] = [];
    if (bodyFn) parts.push(`data: ${bodyFn}`);
    if (qFn)    parts.push(`params: ${qFn}`);
    if (!parts.length) return '';
    return `, {\n    ${parts.join(',\n    ')}\n  }`;
  }

  private fakerValueForField(name: string, def: any): string {
    const n = name.toLowerCase();
    const t = (def?.type ?? 'string').toLowerCase();
    if (n.includes('email'))                            return 'faker.internet.email()';
    if (n.includes('name') && !n.includes('username'))  return 'faker.person.fullName()';
    if (n.includes('username'))                         return 'faker.internet.username()';
    if (n.includes('phone'))                            return 'faker.phone.number()';
    if (n.includes('address') || n.includes('street')) return 'faker.location.streetAddress()';
    if (n.includes('city'))                             return 'faker.location.city()';
    if (n.includes('country'))                          return 'faker.location.countryCode()';
    if (n.includes('zip') || n.includes('postal'))     return 'faker.location.zipCode()';
    if (n.includes('url') || n.includes('website'))    return 'faker.internet.url()';
    if (n.includes('password'))                        return 'faker.internet.password({ length: 12 })';
    if (n.includes('date'))                            return 'faker.date.recent().toISOString()';
    if (n.includes('description') || n.includes('bio')) return 'faker.lorem.sentence()';
    if (n.includes('title'))                           return 'faker.lorem.words(3)';
    if (n.includes('price') || n.includes('amount'))  return 'faker.number.float({ min: 1, max: 999, fractionDigits: 2 })';
    if (t === 'integer' || t === 'number')             return 'faker.number.int({ min: 1, max: 1000 })';
    if (t === 'boolean')                               return 'faker.datatype.boolean()';
    if (t === 'array')                                 return '[]';
    return 'faker.lorem.word()';
  }

  private hasEnumField(ep: ParsedEndpoint): boolean {
    const schema = ep.requestBodySchema;
    if (!schema?.properties) return false;
    return Object.values(schema.properties as Record<string, any>).some(d => d?.enum?.length);
  }

  private expectedStatus(ep: ParsedEndpoint): number {
    const codes = Object.keys(ep.responses).map(Number).filter(n => !isNaN(n)).sort();
    return codes.find(c => c >= 200 && c < 300) ?? 200;
  }

  // ─── Auth fixture ─────────────────────────────────────────────────────────────

  private buildAuthFixture(ext: string, baseUrl: string): GeneratedFile {
    return {
      path: `src/fixtures/api-auth.fixture.${ext}`,
      content: `import { test as base } from '@playwright/test';

const BASE_URL = process.env.API_BASE_URL ?? '${baseUrl}';

export const test = base.extend<{ baseURL: string; authToken: string }>({
  baseURL: async ({}, use) => {
    await use(BASE_URL);
  },
  authToken: async ({ request }, use) => {
    const token = process.env.API_TOKEN ?? '';
    await use(token);
  },
});

export { expect } from '@playwright/test';
`,
    };
  }

  // ─── Data helper files ────────────────────────────────────────────────────────

  private buildFakerHelper(ext: string): GeneratedFile {
    return {
      path: `src/helpers/faker-helper.${ext}`,
      content: `import { faker } from '@faker-js/faker';

export function buildPayload(schema: Record<string, string>): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const [key, type] of Object.entries(schema)) {
    if (type === 'email')   result[key] = faker.internet.email();
    else if (type === 'number') result[key] = faker.number.int({ min: 1, max: 1000 });
    else if (type === 'boolean') result[key] = faker.datatype.boolean();
    else result[key] = faker.lorem.word();
  }
  return result;
}
`,
    };
  }

  private buildCsvHelper(ext: string): GeneratedFile {
    return {
      path: `src/helpers/csv-helper.${ext}`,
      content: `import * as fs from 'fs';
import * as path from 'path';

export function loadCsv(filePath: string): Record<string, string>[] {
  const full    = path.resolve(process.cwd(), filePath);
  if (!fs.existsSync(full)) return [];
  const lines   = fs.readFileSync(full, 'utf-8').split('\\n').filter(Boolean);
  const headers = lines[0].split(',').map(h => h.trim());
  return lines.slice(1).map(line => {
    const values = line.split(',').map(v => v.trim());
    return Object.fromEntries(headers.map((h, i) => [h, values[i] ?? '']));
  });
}
`,
    };
  }

  private buildJsonHelper(ext: string): GeneratedFile {
    return {
      path: `src/helpers/json-helper.${ext}`,
      content: `import * as fs from 'fs';
import * as path from 'path';

export function loadJson<T = Record<string, unknown>>(filePath: string): T[] {
  const full = path.resolve(process.cwd(), filePath);
  if (!fs.existsSync(full)) return [];
  return JSON.parse(fs.readFileSync(full, 'utf-8')) as T[];
}
`,
    };
  }

  private buildSampleDataFile(dataStrat: string, endpoints: ParsedEndpoint[]): GeneratedFile {
    if (dataStrat === 'json') {
      const sample = [{ id: 1, name: 'Sample', email: 'sample@example.com', status: 'active' }];
      return { path: 'testdata/api_data.json', content: JSON.stringify(sample, null, 2) + '\n' };
    }
    const rows = ['endpoint,method,expected_status,name,email,status'];
    for (const ep of endpoints.slice(0, 20)) {
      const ok = this.expectedStatus(ep);
      rows.push(`${ep.path},${ep.method},${ok},Sample User,sample@example.com,active`);
    }
    return { path: 'testdata/api_data.csv', content: rows.join('\n') + '\n' };
  }

  // ─── Utilities ────────────────────────────────────────────────────────────────

  private groupByTag(endpoints: ParsedEndpoint[]): Record<string, ParsedEndpoint[]> {
    const map: Record<string, ParsedEndpoint[]> = {};
    for (const ep of endpoints) {
      if (!map[ep.tag]) map[ep.tag] = [];
      map[ep.tag].push(ep);
    }
    return map;
  }

  private toFileName(tag: string): string {
    return tag.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
  }

  private toMethodName(opId: string): string {
    return opId.replace(/[^a-zA-Z0-9]/g, '_').replace(/_+/g, '_').replace(/^_|_$/g, '');
  }
}
