import { Injectable } from '@nestjs/common';
import type { GeneratedFile } from '../templates/template-engine';
import type { FrameworkBlueprint } from '../blueprint/blueprint.model';
import type { SwaggerSummary, ParsedEndpoint } from '../swagger/swagger.types';

@Injectable()
export class PlaywrightPythonApiTestGeneratorService {

  generate(summary: SwaggerSummary, blueprint: FrameworkBlueprint): GeneratedFile[] {
    const level = blueprint.coverageLevel ?? 'functional';
    const files: GeneratedFile[] = [];
    const byTag = this.groupByTag(summary.endpoints);

    for (const [tag, endpoints] of Object.entries(byTag)) {
      files.push(this.buildTestFile(tag, endpoints, level, summary.baseUrl));
    }

    files.push(this.buildConftest(summary.baseUrl));
    files.push(this.buildRequirements());
    files.push(this.buildPytestIni());
    files.push(this.buildReadme(summary.baseUrl, summary.endpoints.length));
    files.push({ path: 'tests/__init__.py',     content: '' });
    files.push({ path: 'tests/api/__init__.py', content: '' });

    return files;
  }

  // ─── Test file per tag ────────────────────────────────────────────────────────

  private buildTestFile(tag: string, endpoints: ParsedEndpoint[], level: string, baseUrl: string): GeneratedFile {
    const fileName = this.toFileName(tag);
    const tests:   string[] = [];

    for (const ep of endpoints) {
      tests.push(...this.buildTestFunctions(ep, level));
    }

    return {
      path: `tests/api/test_${fileName}_api.py`,
      content: `import os
import pytest
from faker import Faker
from playwright.sync_api import APIRequestContext

# Auto-generated API tests — ${tag}
# Generated by Qlitz Framework Generator

fake = Faker()

pytestmark = [pytest.mark.api]

${tests.join('\n\n')}
`,
    };
  }

  // ─── Test function builders ───────────────────────────────────────────────────

  private buildTestFunctions(ep: ParsedEndpoint, level: string): string[] {
    const tests:  string[] = [];
    const ok      = this.expectedStatus(ep);
    const opId    = this.toFuncId(ep.operationId || `${ep.method}_${ep.path}`);
    const path    = this.buildPath(ep, 'faker');
    const body    = this.buildBody(ep);

    tests.push(this.buildSmokeFunc(ep, opId, ok, path, body));
    if (level === 'smoke') return tests;

    tests.push(this.buildSchemaFunc(ep, opId, ok, path, body));
    tests.push(this.buildResponseTimeFunc(ep, opId, ok, path, body));
    if (ep.method !== 'DELETE') {
      tests.push(this.buildContentTypeFunc(ep, opId, ok, path, body));
    }

    if (ep.requiresAuth) {
      tests.push(this.buildNoAuthFunc(ep, opId));
      tests.push(this.buildInvalidTokenFunc(ep, opId));
    }

    if (['POST', 'PUT', 'PATCH'].includes(ep.method)) {
      tests.push(this.buildEmptyBodyFunc(ep, opId));
      tests.push(this.buildMissingFieldFunc(ep, opId));
      tests.push(this.buildInvalidTypeFunc(ep, opId));
      tests.push(this.buildMalformedJsonFunc(ep, opId));
      if (this.hasEnumField(ep)) {
        tests.push(this.buildInvalidEnumFunc(ep, opId));
      }
    }

    if (ep.parameters.some(p => p.in === 'path')) {
      tests.push(this.buildNotFoundFunc(ep, opId));
    }
    if (ep.method === 'POST') {
      tests.push(this.buildDuplicateFunc(ep, opId, path, body));
    }

    return tests;
  }

  // ── Smoke ────────────────────────────────────────────────────────────────────

  private buildSmokeFunc(ep: ParsedEndpoint, opId: string, ok: number, path: string, body: string): string {
    const bodyLine = body ? `    payload = ${body}\n` : '';
    const dataArg  = body ? ', data=payload' : '';
    return `@pytest.mark.smoke
def test_smoke_${opId}(api_client: APIRequestContext) -> None:
${bodyLine}    response = api_client.${ep.method.toLowerCase()}(${path}${dataArg})
    assert response.status == ${ok}`;
  }

  // ── Functional positive ───────────────────────────────────────────────────────

  private buildSchemaFunc(ep: ParsedEndpoint, opId: string, ok: number, path: string, body: string): string {
    const bodyLine = body ? `    payload = ${body}\n` : '';
    const dataArg  = body ? ', data=payload' : '';
    return `@pytest.mark.functional
def test_functional_${opId}_schema_valid(api_client: APIRequestContext) -> None:
${bodyLine}    response = api_client.${ep.method.toLowerCase()}(${path}${dataArg})
    assert response.status == ${ok}
    assert response.text() != "", "Response body should not be empty"`;
  }

  private buildResponseTimeFunc(ep: ParsedEndpoint, opId: string, ok: number, path: string, body: string): string {
    const bodyLine = body ? `    payload = ${body}\n` : '';
    const dataArg  = body ? ', data=payload' : '';
    return `@pytest.mark.functional
def test_functional_${opId}_response_time(api_client: APIRequestContext) -> None:
    import time
${bodyLine}    start    = time.time()
    response = api_client.${ep.method.toLowerCase()}(${path}${dataArg})
    elapsed  = time.time() - start
    assert response.status == ${ok}
    assert elapsed < 5, f"Response took {elapsed:.2f}s — exceeded 5s limit"`;
  }

  private buildContentTypeFunc(ep: ParsedEndpoint, opId: string, ok: number, path: string, body: string): string {
    const bodyLine = body ? `    payload = ${body}\n` : '';
    const dataArg  = body ? ', data=payload' : '';
    return `@pytest.mark.functional
def test_functional_${opId}_content_type(api_client: APIRequestContext) -> None:
${bodyLine}    response = api_client.${ep.method.toLowerCase()}(${path}${dataArg})
    assert response.status == ${ok}
    ct = response.headers.get("content-type", "")
    assert "application/json" in ct, f"Expected application/json, got: {ct}"`;
  }

  // ── Negative — auth ───────────────────────────────────────────────────────────

  private buildNoAuthFunc(ep: ParsedEndpoint, opId: string): string {
    const path = `"${ep.path.replace(/\{[^}]+\}/g, '1')}"`;
    return `@pytest.mark.functional
def test_security_${opId}_no_auth(playwright) -> None:
    no_auth = playwright.request.new_context(
        base_url=os.getenv("API_BASE_URL", ""))
    response = no_auth.${ep.method.toLowerCase()}(${path})
    assert response.status in [401, 403], f"Expected 401/403, got: {response.status}"
    no_auth.dispose()`;
  }

  private buildInvalidTokenFunc(ep: ParsedEndpoint, opId: string): string {
    const path = `"${ep.path.replace(/\{[^}]+\}/g, '1')}"`;
    return `@pytest.mark.functional
def test_security_${opId}_invalid_token(api_client: APIRequestContext) -> None:
    response = api_client.${ep.method.toLowerCase()}(${path},
        headers={"Authorization": "Bearer invalid-token-xyz"})
    assert response.status in [401, 403], f"Expected 401/403, got: {response.status}"`;
  }

  // ── Negative — input validation ────────────────────────────────────────────────

  private buildEmptyBodyFunc(ep: ParsedEndpoint, opId: string): string {
    const path = `"${ep.path.replace(/\{[^}]+\}/g, '1')}"`;
    return `@pytest.mark.functional
def test_validation_${opId}_empty_body(api_client: APIRequestContext) -> None:
    response = api_client.${ep.method.toLowerCase()}(${path}, data={})
    assert response.status in [400, 422], f"Expected 400/422, got: {response.status}"`;
  }

  private buildMissingFieldFunc(ep: ParsedEndpoint, opId: string): string {
    const path = `"${ep.path.replace(/\{[^}]+\}/g, '1')}"`;
    return `@pytest.mark.functional
def test_validation_${opId}_missing_field(api_client: APIRequestContext) -> None:
    response = api_client.${ep.method.toLowerCase()}(${path}, data={"__invalid__": True})
    assert response.status in [400, 422], f"Expected 400/422, got: {response.status}"`;
  }

  private buildInvalidTypeFunc(ep: ParsedEndpoint, opId: string): string {
    const path = `"${ep.path.replace(/\{[^}]+\}/g, '1')}"`;
    return `@pytest.mark.functional
def test_validation_${opId}_invalid_types(api_client: APIRequestContext) -> None:
    response = api_client.${ep.method.toLowerCase()}(${path},
        data={"id": "not-a-number", "name": 12345, "email": False})
    assert response.status in [400, 422], f"Expected 400/422, got: {response.status}"`;
  }

  private buildMalformedJsonFunc(ep: ParsedEndpoint, opId: string): string {
    const path = `"${ep.path.replace(/\{[^}]+\}/g, '1')}"`;
    return `@pytest.mark.functional
def test_validation_${opId}_malformed_json(playwright) -> None:
    ctx = playwright.request.new_context(
        base_url=os.getenv("API_BASE_URL", ""),
        extra_http_headers={"Content-Type": "application/json",
                            "Authorization": f"Bearer {os.getenv('API_TOKEN', '')}"})
    response = ctx.fetch(${path}, method="${ep.method}", data="{malformed-json")
    assert response.status in [400, 415, 422], f"Expected 400/415/422, got: {response.status}"
    ctx.dispose()`;
  }

  private buildInvalidEnumFunc(ep: ParsedEndpoint, opId: string): string {
    const path = `"${ep.path.replace(/\{[^}]+\}/g, '1')}"`;
    return `@pytest.mark.functional
def test_validation_${opId}_invalid_enum(api_client: APIRequestContext) -> None:
    response = api_client.${ep.method.toLowerCase()}(${path},
        data={"status": "__INVALID_ENUM_VALUE__"})
    assert response.status in [400, 422], f"Expected 400/422, got: {response.status}"`;
  }

  // ── Negative — resource ────────────────────────────────────────────────────────

  private buildNotFoundFunc(ep: ParsedEndpoint, opId: string): string {
    const path = `"${ep.path.replace(/\{[^}]+\}/g, '999999999')}"`;
    return `@pytest.mark.functional
def test_negative_${opId}_not_found(api_client: APIRequestContext) -> None:
    response = api_client.${ep.method.toLowerCase()}(${path})
    assert response.status in [404, 400], f"Expected 404/400, got: {response.status}"`;
  }

  private buildDuplicateFunc(ep: ParsedEndpoint, opId: string, path: string, body: string): string {
    const bodyLine = body ? `    payload = ${body}\n` : '';
    const dataArg  = body ? ', data=payload' : '';
    return `@pytest.mark.functional
def test_negative_${opId}_duplicate(api_client: APIRequestContext) -> None:
${bodyLine}    api_client.post(${path}${dataArg})
    response = api_client.post(${path}${dataArg})
    assert response.status in [409, 400, 422], f"Expected 409/400/422, got: {response.status}"`;
  }

  // ─── Shared infrastructure ────────────────────────────────────────────────────

  private buildConftest(baseUrl: string): GeneratedFile {
    return {
      path: 'conftest.py',
      content: `import os
import pytest
from playwright.sync_api import Playwright


def pytest_configure(config) -> None:
    config.addinivalue_line("markers", "smoke: fast happy-path check")
    config.addinivalue_line("markers", "functional: full positive + negative coverage")
    config.addinivalue_line("markers", "api: API-level tests")


@pytest.fixture(scope="session")
def api_client(playwright: Playwright):
    context = playwright.request.new_context(
        base_url=os.getenv("API_BASE_URL", "${baseUrl}"),
        extra_http_headers={
            "Authorization": f"Bearer {os.getenv('API_TOKEN', '')}",
            "Content-Type": "application/json",
        },
    )
    yield context
    context.dispose()
`,
    };
  }

  private buildRequirements(): GeneratedFile {
    return {
      path: 'requirements.txt',
      content: `playwright>=1.44.0
pytest>=8.0.0
pytest-playwright>=0.4.4
Faker>=25.0.0
`,
    };
  }

  private buildPytestIni(): GeneratedFile {
    return {
      path: 'pytest.ini',
      content: `[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
`,
    };
  }

  private buildReadme(baseUrl: string, endpointCount: number): GeneratedFile {
    return {
      path: 'README.md',
      content: `# Playwright Python API Test Suite

Auto-generated by Qlitz · ${endpointCount} endpoint(s) · Base URL: \`${baseUrl}\`

## Prerequisites
- Python 3.11+
- pip

## Setup
\`\`\`bash
pip install -r requirements.txt
playwright install
\`\`\`

## Running Tests
\`\`\`bash
# All API tests
pytest -m api

# Smoke only
pytest -m "smoke and api"

# Functional only
pytest -m "functional and api"

# Set base URL and token
API_BASE_URL=https://api.your-site.com API_TOKEN=your-token pytest
\`\`\`

## Project Structure
\`\`\`
tests/api/
  test_*_api.py     One file per Swagger tag
conftest.py         Session-scoped api_client fixture
\`\`\`
`,
    };
  }

  // ─── Helpers ──────────────────────────────────────────────────────────────────

  private buildPath(ep: ParsedEndpoint, mode: 'faker' | 'literal'): string {
    const withParams = ep.path.replace(/\{[^}]+\}/g,
      mode === 'faker' ? `{fake.random_int(min=1, max=1000)}` : '1'
    );
    return `f"${withParams}"`;
  }

  private buildBody(ep: ParsedEndpoint): string {
    if (!['POST', 'PUT', 'PATCH'].includes(ep.method) || !ep.requestBodySchema) return '';
    const props   = ep.requestBodySchema?.properties ?? {};
    const entries = Object.entries(props as Record<string, any>);
    if (!entries.length) return '{}';

    const lines = entries.map(([key, def]) =>
      `    "${key}": ${this.pyFake(key, def)}`
    ).join(',\n');
    return `{\n${lines}\n}`;
  }

  private pyFake(name: string, def: any): string {
    const n = name.toLowerCase();
    const t = (def?.type ?? 'string').toLowerCase();
    if (n.includes('email'))                           return 'fake.email()';
    if (n.includes('name') && !n.includes('username')) return 'fake.name()';
    if (n.includes('username'))                        return 'fake.user_name()';
    if (n.includes('phone'))                           return 'fake.phone_number()';
    if (n.includes('address') || n.includes('street')) return 'fake.address()';
    if (n.includes('city'))                            return 'fake.city()';
    if (n.includes('url') || n.includes('website'))   return 'fake.url()';
    if (n.includes('password'))                        return 'fake.password()';
    if (n.includes('date'))                            return 'fake.date()';
    if (n.includes('title'))                           return 'fake.sentence(nb_words=3)';
    if (n.includes('description'))                     return 'fake.sentence()';
    if (n.includes('price') || n.includes('amount'))  return 'round(fake.random.uniform(1, 999), 2)';
    if (t === 'integer' || t === 'number')             return 'fake.random_int(min=1, max=1000)';
    if (t === 'boolean')                               return 'fake.boolean()';
    if (t === 'array')                                 return '[]';
    return 'fake.word()';
  }

  private hasEnumField(ep: ParsedEndpoint): boolean {
    const props = ep.requestBodySchema?.properties;
    if (!props) return false;
    return Object.values(props as Record<string, any>).some((d: any) => d?.enum?.length);
  }

  private expectedStatus(ep: ParsedEndpoint): number {
    const codes = Object.keys(ep.responses).map(Number).filter(n => !isNaN(n)).sort();
    return codes.find(c => c >= 200 && c < 300) ?? 200;
  }

  private groupByTag(endpoints: ParsedEndpoint[]): Record<string, ParsedEndpoint[]> {
    const map: Record<string, ParsedEndpoint[]> = {};
    for (const ep of endpoints) {
      if (!map[ep.tag]) map[ep.tag] = [];
      map[ep.tag].push(ep);
    }
    return map;
  }

  private toFileName(tag: string): string {
    return tag.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '');
  }

  private toFuncId(opId: string): string {
    return opId.toLowerCase().replace(/[^a-z0-9]/g, '_').replace(/_+/g, '_').replace(/^_|_$/g, '');
  }
}
