apiVersion: v1
kind: Service
metadata:
  name: {{GRID_SERVICE_NAME}}
  namespace: {{K8S_NAMESPACE}}
  labels:
    app: {{GRID_SERVICE_NAME}}
    app.kubernetes.io/managed-by: qlitz
spec:
  selector:
    app: {{GRID_SERVICE_NAME}}
  ports:
    - name: hub
      port: 4444
      targetPort: 4444
    - name: publish
      port: 4442
      targetPort: 4442
    - name: subscribe
      port: 4443
      targetPort: 4443
  type: ClusterIP
