import { FrameworkNode, FrameworkRef, defineNode } from '../node.model';

const UI_FRAMEWORKS: FrameworkRef[] = ['selenium', 'cypress', 'playwright', 'webdriverio', 'appium'];

export const DISTRIBUTED_NODES: FrameworkNode[] = [

  defineNode({
    id: 'selenium-java-grid4',
    label: 'Selenium Grid 4',
    category: 'distributed',
    compatibleFrameworks: ['selenium'],
    compatibleLanguages: ['java'],
    templates: ['selenium/java/grid4/base'],
    metadata: {
      description: 'Selenium Grid 4 distributed execution for Selenium + Java. Hub-node topology with Docker Compose configuration.',
      version: '4.x',
      tags: ['selenium-grid', 'distributed', 'parallel', 'docker'],
      docs: 'https://www.selenium.dev/documentation/grid/',
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: ['selenium-java-testng'],
      conflicts: ['selenium-java-zalenium', 'all-lambdatest', 'all-saucelabs'],
      recommendedWith: [],
    },
    capabilities: { canBeRoot: false, supportsParallel: true, supportsDistributed: true, hasAIIntegration: false, hasReporting: false, hasRetry: false },
    configSchema: {
      hubUrl: { type: 'string', label: 'Grid Hub URL', default: 'http://localhost:4444' },
      threadCount: { type: 'number', label: 'Parallel threads', default: 4 },
    },
  }),

  defineNode({
    id: 'selenium-java-zalenium',
    label: 'Zalenium',
    category: 'distributed',
    compatibleFrameworks: ['selenium'],
    compatibleLanguages: ['java'],
    templates: ['selenium/java/zalenium/base'],
    metadata: {
      description: 'Zalenium disposable Selenium Grid with video recording, live preview, and Sauce/BrowserStack integration.',
      version: '3.x',
      tags: ['zalenium', 'selenium-grid', 'video', 'distributed'],
      docs: 'https://opensource.zalando.com/zalenium/',
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: [],
      conflicts: ['selenium-java-grid4', 'all-lambdatest', 'all-saucelabs'],
      recommendedWith: [],
    },
    capabilities: { canBeRoot: false, supportsParallel: true, supportsDistributed: true, hasAIIntegration: false, hasReporting: false, hasRetry: false },
  }),

  defineNode({
    id: 'playwright-ts-sharding',
    label: 'Playwright Sharding',
    category: 'distributed',
    compatibleFrameworks: ['playwright'],
    compatibleLanguages: ['typescript', 'javascript'],
    templates: ['playwright/ts/sharding/base'],
    metadata: {
      description: 'Playwright built-in sharding for distributing tests across CI machines. Shard index configuration and merge-reports.',
      version: '1.x',
      tags: ['sharding', 'playwright', 'distributed', 'ci'],
      docs: 'https://playwright.dev/docs/test-sharding',
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: ['playwright-ts-runner'],
      conflicts: [],
      recommendedWith: ['ci-github-actions', 'ci-gitlab'],
    },
    capabilities: { canBeRoot: false, supportsParallel: true, supportsDistributed: true, hasAIIntegration: false, hasReporting: false, hasRetry: false },
    configSchema: {
      totalShards: { type: 'number', label: 'Total shards', default: 4 },
    },
  }),

  defineNode({
    id: 'cypress-ts-cloud',
    label: 'Cypress Cloud',
    category: 'distributed',
    compatibleFrameworks: ['cypress'],
    compatibleLanguages: ['typescript', 'javascript'],
    templates: ['cypress/ts/cloud/base'],
    metadata: {
      description: 'Cypress Cloud (formerly Cypress Dashboard) for parallelization, test analytics, flake detection, and CI integration.',
      version: '13.x',
      tags: ['cypress-cloud', 'parallelization', 'flake', 'analytics'],
      docs: 'https://docs.cypress.io/cloud/overview/getting-started',
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: ['cypress-ts-runner'],
      conflicts: [],
      recommendedWith: [],
    },
    capabilities: { canBeRoot: false, supportsParallel: true, supportsDistributed: true, hasAIIntegration: false, hasReporting: true, hasRetry: false },
  }),

  defineNode({
    id: 'all-lambdatest',
    label: 'LambdaTest',
    category: 'distributed',
    compatibleFrameworks: UI_FRAMEWORKS,
    compatibleLanguages: ['*'],
    templates: ['distributed/lambdatest/base'],
    metadata: {
      description: 'LambdaTest cloud cross-browser testing platform. 3000+ real browser/OS combinations with HyperExecute for speed.',
      version: 'latest',
      tags: ['lambdatest', 'cloud', 'cross-browser', 'distributed'],
      docs: 'https://www.lambdatest.com/support/docs/',
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: [],
      conflicts: ['selenium-java-grid4', 'selenium-java-zalenium', 'all-saucelabs'],
      recommendedWith: [],
    },
    capabilities: { canBeRoot: false, supportsParallel: true, supportsDistributed: true, hasAIIntegration: false, hasReporting: true, hasRetry: false },
  }),

  defineNode({
    id: 'all-saucelabs',
    label: 'Sauce Labs',
    category: 'distributed',
    compatibleFrameworks: UI_FRAMEWORKS,
    compatibleLanguages: ['*'],
    templates: ['distributed/saucelabs/base'],
    metadata: {
      description: 'Sauce Labs cloud testing platform with real device testing, live testing, and saucelabs.com reporting.',
      version: 'latest',
      tags: ['saucelabs', 'cloud', 'real-devices', 'distributed'],
      docs: 'https://docs.saucelabs.com/',
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: [],
      conflicts: ['selenium-java-grid4', 'selenium-java-zalenium', 'all-lambdatest'],
      recommendedWith: [],
    },
    capabilities: { canBeRoot: false, supportsParallel: true, supportsDistributed: true, hasAIIntegration: false, hasReporting: true, hasRetry: false },
  }),

  // ─── Docker / Compose / K8s ───────────────────────────────────────────────

  defineNode({
    id: 'distributed-docker',
    label: 'Docker (Local)',
    category: 'distributed',
    compatibleFrameworks: ['selenium'],
    compatibleLanguages: ['java'],
    templates: ['shared/distributed/docker/base'],
    metadata: {
      description: 'Run tests inside a Docker container with JDK, Maven, and Chrome preconfigured. Single-command execution.',
      version: 'latest',
      tags: ['docker', 'containerised', 'local', 'selenium', 'java'],
      docs: 'https://docs.docker.com/',
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: [],
      conflicts: ['distributed-docker-compose-grid', 'distributed-k8s-grid'],
      recommendedWith: ['selenium-java-pom'],
    },
    capabilities: { canBeRoot: false, supportsParallel: false, supportsDistributed: true, hasAIIntegration: false, hasReporting: false, hasRetry: false },
    configSchema: {
      imageName: { type: 'string', label: 'Docker image name', default: 'qlitz-tests', required: true },
      imageTag:  { type: 'string', label: 'Image tag',         default: 'latest' },
    },
  }),

  defineNode({
    id: 'distributed-docker-compose-grid',
    label: 'Docker Compose + Grid',
    category: 'distributed',
    compatibleFrameworks: ['selenium'],
    compatibleLanguages: ['java'],
    templates: ['selenium/java/distributed/docker-compose-grid'],
    metadata: {
      description: 'Docker Compose stack: Selenium Grid 4 hub + Chrome/Firefox nodes + test runner service. Full local grid in one command.',
      version: '4.x',
      tags: ['docker-compose', 'selenium-grid', 'grid4', 'distributed', 'parallel'],
      docs: 'https://github.com/SeleniumHQ/docker-selenium',
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: [],
      conflicts: ['distributed-docker', 'distributed-k8s-grid', 'all-lambdatest', 'all-saucelabs'],
      recommendedWith: ['selenium-java-pom', 'selenium-java-testng'],
    },
    capabilities: { canBeRoot: false, supportsParallel: true, supportsDistributed: true, hasAIIntegration: false, hasReporting: false, hasRetry: false },
    configSchema: {
      imageName:     { type: 'string', label: 'Test runner image name', default: 'qlitz-tests', required: true },
      imageTag:      { type: 'string', label: 'Image tag',              default: 'latest' },
      gridHubPort:   { type: 'number', label: 'Grid hub port',          default: 4444 },
      nodeCount:     { type: 'number', label: 'Browser nodes per type', default: 2 },
      gridHubUrl:    { type: 'string', label: 'Grid hub URL (internal)',  default: 'http://selenium-hub:4444' },
    },
  }),

  defineNode({
    id: 'distributed-k8s-grid',
    label: 'Kubernetes + Grid',
    category: 'distributed',
    compatibleFrameworks: ['selenium'],
    compatibleLanguages: ['java'],
    templates: ['selenium/java/distributed/k8s-grid'],
    metadata: {
      description: 'Kubernetes manifests: Selenium Grid 4 hub deployment, browser node deployments, services, configmap, and test runner Job.',
      version: '4.x',
      tags: ['kubernetes', 'k8s', 'selenium-grid', 'cluster', 'distributed'],
      docs: 'https://www.selenium.dev/documentation/grid/getting_started/',
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: [],
      conflicts: ['distributed-docker', 'distributed-docker-compose-grid'],
      recommendedWith: ['ci-github-actions', 'ci-gitlab'],
    },
    capabilities: { canBeRoot: false, supportsParallel: true, supportsDistributed: true, hasAIIntegration: false, hasReporting: false, hasRetry: false },
    configSchema: {
      namespace:       { type: 'string', label: 'K8s namespace',         default: 'qa-automation', required: true },
      imageName:       { type: 'string', label: 'Test runner image name', default: 'qlitz-tests' },
      imageTag:        { type: 'string', label: 'Image tag',              default: 'latest' },
      gridServiceName: { type: 'string', label: 'Grid service name',      default: 'selenium-hub' },
      nodeReplicas:    { type: 'number', label: 'Browser node replicas',  default: 2 },
    },
  }),

  defineNode({
    id: 'playwright-ts-docker',
    label: 'Docker (Local)',
    category: 'distributed',
    compatibleFrameworks: ['playwright'],
    compatibleLanguages: ['typescript', 'javascript'],
    templates: ['playwright/ts/distributed/docker/base'],
    metadata: {
      description: 'Dockerfile for Playwright + TypeScript. Node 20, all Playwright browsers bundled, ready for CI or local container runs.',
      version: '1.x',
      tags: ['docker', 'playwright', 'typescript', 'containerised'],
      docs: 'https://playwright.dev/docs/docker',
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: [],
      conflicts: [],
      recommendedWith: ['playwright-ts-pom', 'ci-github-actions'],
    },
    capabilities: { canBeRoot: false, supportsParallel: true, supportsDistributed: true, hasAIIntegration: false, hasReporting: false, hasRetry: false },
    configSchema: {
      imageName: { type: 'string', label: 'Docker image name', default: 'qlitz-playwright', required: true },
      imageTag:  { type: 'string', label: 'Image tag',         default: 'latest' },
    },
  }),

  defineNode({
    id: 'distributed-browserstack',
    label: 'BrowserStack',
    category: 'distributed',
    compatibleFrameworks: UI_FRAMEWORKS,
    compatibleLanguages: ['*'],
    templates: ['distributed/browserstack/base'],
    metadata: {
      description: 'BrowserStack Automate for cross-browser/device testing on 3500+ real browsers and devices.',
      version: 'latest',
      tags: ['browserstack', 'cloud', 'cross-browser', 'real-devices', 'distributed'],
      docs: 'https://www.browserstack.com/docs/automate',
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: [],
      conflicts: ['selenium-java-grid4', 'selenium-java-zalenium', 'all-lambdatest', 'all-saucelabs'],
      recommendedWith: [],
    },
    capabilities: { canBeRoot: false, supportsParallel: true, supportsDistributed: true, hasAIIntegration: false, hasReporting: true, hasRetry: false },
    configSchema: {
      projectName: { type: 'string', label: 'BrowserStack project name', default: 'Qlitz UI Suite' },
      buildName:   { type: 'string', label: 'Build name / label',        default: 'Nightly Regression' },
    },
  }),

  defineNode({
    id: 'cypress-ts-docker',
    label: 'Docker (Local)',
    category: 'distributed',
    compatibleFrameworks: ['cypress'],
    compatibleLanguages: ['typescript', 'javascript'],
    templates: ['cypress/ts/distributed/docker/base'],
    metadata: {
      description: 'Dockerfile for Cypress + TypeScript using the official cypress/included image. No browser install needed.',
      version: '13.x',
      tags: ['docker', 'cypress', 'typescript', 'containerised'],
      docs: 'https://docs.cypress.io/guides/continuous-integration/introduction#Docker',
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: [],
      conflicts: [],
      recommendedWith: ['cypress-ts-page-objects', 'ci-github-actions'],
    },
    capabilities: { canBeRoot: false, supportsParallel: false, supportsDistributed: true, hasAIIntegration: false, hasReporting: false, hasRetry: false },
    configSchema: {
      imageName: { type: 'string', label: 'Docker image name', default: 'qlitz-cypress', required: true },
      imageTag:  { type: 'string', label: 'Image tag',         default: 'latest' },
    },
  }),

  // ─── REST Assured distributed ────────────────────────────────────────────────

  defineNode({
    id: 'restassured-java-k8s',
    label: 'Kubernetes Job',
    category: 'distributed',
    compatibleFrameworks: ['restassured'],
    compatibleLanguages: ['java'],
    templates: ['restassured/java/k8s'],
    metadata: {
      description: 'Kubernetes batch Job manifest for REST Assured + Java. Runs mvn clean test in a Maven container — credentials injected via K8s Secrets. No Grid needed: API tests are stateless.',
      version: 'latest',
      tags: ['kubernetes', 'k8s', 'job', 'restassured', 'maven'],
      docs: 'https://kubernetes.io/docs/concepts/workloads/controllers/job/',
      since: '1.0.0',
    },
    constraints: {
      required: false, maxInstances: 1, requires: [],
      conflicts: ['restassured-java-docker'],
      recommendedWith: ['restassured-java-github-actions', 'restassured-java-gitlab'],
    },
    capabilities: { canBeRoot: false, supportsParallel: true, supportsDistributed: true, hasAIIntegration: false, hasReporting: false, hasRetry: false },
    configSchema: {
      namespace:   { type: 'string', label: 'K8s namespace',     default: 'qa-automation', required: true },
      imageName:   { type: 'string', label: 'Maven image',        default: 'maven:3.9-eclipse-temurin-17' },
    },
  }),

  defineNode({
    id: 'restassured-java-docker',
    label: 'Docker Compose',
    category: 'distributed',
    compatibleFrameworks: ['restassured'],
    compatibleLanguages: ['java'],
    templates: ['restassured/java/docker'],
    metadata: {
      description: 'Docker Compose setup for REST Assured + Java. Runs the full Maven test suite inside a container — auth token and base URL injected as environment variables. One command: docker-compose run --rm api-tests.',
      version: '3.x',
      tags: ['docker', 'compose', 'container', 'restassured', 'maven'],
      docs: 'https://docs.docker.com/compose/',
      since: '1.0.0',
    },
    constraints: { required: false, maxInstances: 1, requires: [], conflicts: [], recommendedWith: [] },
    capabilities: { canBeRoot: false, supportsParallel: false, supportsDistributed: true, hasAIIntegration: false, hasReporting: false, hasRetry: false },
  }),

];
