#!/bin/bash
# Generated by Qlitz Framework Generator
# Spin up Grid + run tests + tear down
set -euo pipefail

PROJECT="{{PROJECT_NAME}}"
GRID_URL="{{GRID_HUB_URL}}"

echo "▶ Starting Selenium Grid..."
docker compose up -d selenium-hub chrome-node firefox-node

echo "⏳ Waiting for Grid to be ready..."
until curl -sf "${GRID_URL}/wd/hub/status" | grep -q '"ready":true'; do
  sleep 3
  echo "   still waiting..."
done
echo "✓ Grid is ready at ${GRID_URL}"

echo "▶ Running tests..."
docker compose run --rm \
  -e GRID_URL="${GRID_URL}" \
  -e BASE_URL="${BASE_URL:-{{BASE_URL}}}" \
  -e BROWSER="${BROWSER:-{{BROWSER}}}" \
  test-runner

EXIT_CODE=$?

echo "▶ Tearing down Grid..."
docker compose down

exit ${EXIT_CODE}
