#!/usr/bin/env bash
# Run Playwright tests for {{PROJECT_NAME}}
# Framework: Playwright {{FRAMEWORK}} | Language: {{LANGUAGE}}
# Generated by Qlitz Framework Generator

set -e

BASE_URL="${BASE_URL:-{{BASE_URL}}}"
BROWSER="${BROWSER:-{{BROWSER}}}"
WORKERS="${WORKERS:-{{THREAD_COUNT}}}"
HEADLESS="${HEADLESS:-{{HEADLESS}}}"

echo "▶ Running Playwright tests"
echo "  Base URL  : $BASE_URL"
echo "  Browser   : $BROWSER"
echo "  Workers   : $WORKERS"
echo "  Headless  : $HEADLESS"

npx playwright test \
  --project="$BROWSER" \
  --workers="$WORKERS" \
  ${HEADLESS:+--headed=false}
