import { FrameworkNode, defineNode } from '../node.model';

export const REPORTING_NODES: FrameworkNode[] = [

  defineNode({
    id: 'selenium-java-allure',
    label: 'Allure Report',
    category: 'reporting',
    compatibleFrameworks: ['selenium'],
    compatibleLanguages: ['java'],
    templates: ['selenium/java/allure/base'],
    metadata: {
      description: 'Allure 2 reporting for Selenium + Java. Rich HTML reports with steps, attachments, environment info, and trend charts.',
      version: '2.x',
      tags: ['allure', 'html-report', 'steps', 'attachments', 'trend'],
      docs: 'https://allurereport.org/docs/selenium/',
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: [],
      conflicts: ['selenium-java-extent'],
      recommendedWith: ['selenium-java-testng'],
    },
    capabilities: { canBeRoot: false, supportsParallel: false, supportsDistributed: false, hasAIIntegration: false, hasReporting: true, hasRetry: false },
  }),

  defineNode({
    id: 'selenium-java-extent',
    label: 'Extent Reports',
    category: 'reporting',
    compatibleFrameworks: ['selenium'],
    compatibleLanguages: ['java'],
    templates: ['selenium/java/extent/base'],
    metadata: {
      description: 'Extent Reports 5 for Selenium + Java. Fluent API for rich HTML reports with category tagging and test logs.',
      version: '5.x',
      tags: ['extent', 'html-report', 'fluent-api'],
      docs: 'https://www.extentreports.com/docs/versions/5/java/index.html',
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: [],
      conflicts: ['selenium-java-allure'],
      recommendedWith: ['selenium-java-testng'],
    },
    capabilities: { canBeRoot: false, supportsParallel: false, supportsDistributed: false, hasAIIntegration: false, hasReporting: true, hasRetry: false },
  }),

  defineNode({
    id: 'playwright-ts-allure',
    label: 'Allure Report',
    category: 'reporting',
    compatibleFrameworks: ['playwright'],
    compatibleLanguages: ['typescript', 'javascript'],
    templates: ['playwright/ts/allure/base'],
    metadata: {
      description: 'Allure 2 reporter for Playwright + TypeScript via allure-playwright plugin.',
      version: '2.x',
      tags: ['allure', 'playwright', 'typescript'],
      docs: 'https://allurereport.org/docs/playwright/',
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: ['playwright-ts-runner'],
      conflicts: [],
      recommendedWith: [],
    },
    capabilities: { canBeRoot: false, supportsParallel: false, supportsDistributed: false, hasAIIntegration: false, hasReporting: true, hasRetry: false },
  }),

  defineNode({
    id: 'playwright-ts-html',
    label: 'Playwright HTML Reporter',
    category: 'reporting',
    compatibleFrameworks: ['playwright'],
    compatibleLanguages: ['typescript', 'javascript'],
    templates: ['playwright/ts/html-reporter/base'],
    metadata: {
      description: 'Playwright\'s built-in HTML reporter. Zero-config, interactive, includes traces and screenshots.',
      version: '1.x',
      tags: ['html-reporter', 'playwright', 'built-in', 'traces'],
      docs: 'https://playwright.dev/docs/test-reporters#html-reporter',
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: ['playwright-ts-runner'],
      conflicts: [],
      recommendedWith: [],
    },
    capabilities: { canBeRoot: false, supportsParallel: false, supportsDistributed: false, hasAIIntegration: false, hasReporting: true, hasRetry: false },
  }),

  defineNode({
    id: 'playwright-java-allure',
    label: 'Allure Report',
    category: 'reporting',
    compatibleFrameworks: ['playwright'],
    compatibleLanguages: ['java'],
    templates: ['playwright/java/allure/base'],
    metadata: {
      description: 'Allure 2 reporting for Playwright + Java.',
      version: '2.x',
      tags: ['allure', 'playwright', 'java'],
      since: '1.0.0',
    },
    constraints: { required: false, maxInstances: 1, requires: [], conflicts: [], recommendedWith: [] },
    capabilities: { canBeRoot: false, supportsParallel: false, supportsDistributed: false, hasAIIntegration: false, hasReporting: true, hasRetry: false },
  }),

  defineNode({
    id: 'playwright-python-allure',
    label: 'Allure Report',
    category: 'reporting',
    compatibleFrameworks: ['playwright'],
    compatibleLanguages: ['python'],
    templates: ['playwright/python/allure/base'],
    metadata: {
      description: 'Allure 2 reporting for Playwright + Python via allure-pytest.',
      version: '2.x',
      tags: ['allure', 'playwright', 'python'],
      since: '1.0.0',
    },
    constraints: { required: false, maxInstances: 1, requires: [], conflicts: [], recommendedWith: [] },
    capabilities: { canBeRoot: false, supportsParallel: false, supportsDistributed: false, hasAIIntegration: false, hasReporting: true, hasRetry: false },
  }),

  defineNode({
    id: 'playwright-csharp-allure',
    label: 'Allure Report',
    category: 'reporting',
    compatibleFrameworks: ['playwright'],
    compatibleLanguages: ['csharp'],
    templates: ['playwright/csharp/allure/base'],
    metadata: {
      description: 'Allure 2 reporting for Playwright + C# via Allure.NUnit package.',
      version: '2.x',
      tags: ['allure', 'playwright', 'csharp'],
      since: '1.0.0',
    },
    constraints: { required: false, maxInstances: 1, requires: [], conflicts: [], recommendedWith: [] },
    capabilities: { canBeRoot: false, supportsParallel: false, supportsDistributed: false, hasAIIntegration: false, hasReporting: true, hasRetry: false },
  }),

  defineNode({
    id: 'cypress-ts-allure',
    label: 'Allure Report',
    category: 'reporting',
    compatibleFrameworks: ['cypress'],
    compatibleLanguages: ['typescript', 'javascript'],
    templates: ['cypress/ts/allure/base'],
    metadata: {
      description: 'Allure 2 reporter for Cypress via @shelex/cypress-allure-plugin.',
      version: '2.x',
      tags: ['allure', 'cypress', 'typescript'],
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: ['cypress-ts-runner'],
      conflicts: ['cypress-ts-mochawesome'],
      recommendedWith: [],
    },
    capabilities: { canBeRoot: false, supportsParallel: false, supportsDistributed: false, hasAIIntegration: false, hasReporting: true, hasRetry: false },
  }),

  defineNode({
    id: 'cypress-ts-mochawesome',
    label: 'Mochawesome',
    category: 'reporting',
    compatibleFrameworks: ['cypress'],
    compatibleLanguages: ['typescript', 'javascript'],
    templates: ['cypress/ts/mochawesome/base'],
    metadata: {
      description: 'Mochawesome HTML reporter for Cypress. Clean UI, screenshot embedding, and JSON output.',
      version: '7.x',
      tags: ['mochawesome', 'cypress', 'html-report'],
      since: '1.0.0',
    },
    constraints: {
      required: false,
      maxInstances: 1,
      requires: ['cypress-ts-runner'],
      conflicts: ['cypress-ts-allure'],
      recommendedWith: [],
    },
    capabilities: { canBeRoot: false, supportsParallel: false, supportsDistributed: false, hasAIIntegration: false, hasReporting: true, hasRetry: false },
  }),

  defineNode({
    id: 'selenium-python-allure',
    label: 'Allure Report',
    category: 'reporting',
    compatibleFrameworks: ['selenium'],
    compatibleLanguages: ['python'],
    templates: ['selenium/python/allure/base'],
    metadata: {
      description: 'Allure 2 reporting for Selenium + Python via allure-pytest.',
      version: '2.x',
      tags: ['allure', 'selenium', 'python'],
      since: '1.0.0',
    },
    constraints: { required: false, maxInstances: 1, requires: [], conflicts: [], recommendedWith: [] },
    capabilities: { canBeRoot: false, supportsParallel: false, supportsDistributed: false, hasAIIntegration: false, hasReporting: true, hasRetry: false },
  }),

  defineNode({
    id: 'selenium-csharp-allure',
    label: 'Allure Report',
    category: 'reporting',
    compatibleFrameworks: ['selenium'],
    compatibleLanguages: ['csharp'],
    templates: ['selenium/csharp/allure/base'],
    metadata: {
      description: 'Allure 2 reporting for Selenium + C# via Allure.NUnit.',
      version: '2.x',
      tags: ['allure', 'selenium', 'csharp'],
      since: '1.0.0',
    },
    constraints: { required: false, maxInstances: 1, requires: [], conflicts: [], recommendedWith: [] },
    capabilities: { canBeRoot: false, supportsParallel: false, supportsDistributed: false, hasAIIntegration: false, hasReporting: true, hasRetry: false },
  }),

];
