"""
Example test for {{PROJECT_NAME}}
Framework: {{FRAMEWORK}} | Language: {{LANGUAGE}}
Generated by Qlitz Framework Generator
"""
import pytest
from pages.base_page import BasePage


@pytest.mark.smoke
def test_page_loads(driver, base_url):
    page = BasePage(driver)
    page.open(base_url)
    assert driver.title != "", "Page title should not be empty"


@pytest.mark.regression
def test_page_url_matches(driver, base_url):
    driver.get(base_url)
    assert base_url.rstrip("/") in driver.current_url
