"""
Root conftest.py for {{PROJECT_NAME}}
Framework: {{FRAMEWORK}} | Language: {{LANGUAGE}}
Generated by Qlitz Framework Generator
"""
import pytest
from selenium import webdriver
from selenium.webdriver.chrome.options import Options as ChromeOptions
from selenium.webdriver.firefox.options import Options as FirefoxOptions
from webdriver_manager.chrome import ChromeDriverManager
from webdriver_manager.firefox import GeckoDriverManager
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.firefox.service import Service as FirefoxService


def pytest_addoption(parser):
    parser.addoption("--browser",  default="{{BROWSER}}", help="Browser to run tests on")
    parser.addoption("--base-url", default="{{BASE_URL}}", help="Application base URL")
    parser.addoption("--headless", default="{{HEADLESS}}", help="Run headless (true/false)")


@pytest.fixture(scope="session")
def base_url(request):
    return request.config.getoption("--base-url")


@pytest.fixture(scope="function")
def driver(request):
    browser  = request.config.getoption("--browser").lower()
    headless = request.config.getoption("--headless").lower() == "true"

    if browser == "firefox":
        opts = FirefoxOptions()
        if headless:
            opts.add_argument("--headless")
        d = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()), options=opts)
    else:
        opts = ChromeOptions()
        if headless:
            opts.add_argument("--headless=new")
        opts.add_argument("--no-sandbox")
        opts.add_argument("--disable-dev-shm-usage")
        d = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()), options=opts)

    d.implicitly_wait({{TIMEOUT}} / 1000)
    d.maximize_window()
    yield d
    d.quit()
