#!/usr/bin/env bash
# Run Cypress tests for {{PROJECT_NAME}}
# Framework: Cypress | Language: {{LANGUAGE}}
# Generated by Qlitz Framework Generator

set -e

BASE_URL="${CYPRESS_BASE_URL:-{{BASE_URL}}}"
BROWSER="${BROWSER:-{{BROWSER}}}"

echo "▶ Running Cypress tests"
echo "  Base URL : $BASE_URL"
echo "  Browser  : $BROWSER"

npx cypress run \
  --browser "$BROWSER" \
  --config baseUrl="$BASE_URL"
