#!/bin/bash
# Generated by Qlitz Framework Generator
set -euo pipefail

echo "╔══════════════════════════════════════════╗"
echo "║   {{PROJECT_NAME}} — Docker Test Runner  ║"
echo "╚══════════════════════════════════════════╝"

exec mvn test \
  -Dbrowser="${BROWSER:-{{BROWSER}}}" \
  -DbaseUrl="${BASE_URL:-{{BASE_URL}}}" \
  -Dheadless="${HEADLESS:-true}" \
  -Dthread.count="${THREAD_COUNT:-{{THREAD_COUNT}}}" \
  "$@"
