// All AI prompt strings live here so they can be reviewed, versioned,
// and tuned without touching service logic.

export const AI_SYSTEM_DOC_WRITER = `\
You are a senior QA engineer and technical writer.
Your job is to write clear, concise, developer-friendly documentation for
auto-generated test automation frameworks.
Write in plain English. Use Markdown.
Focus on HOW to use the framework, not what it is made of.
No excessive praise, no filler sentences.`;

export const AI_SYSTEM_HEADER_WRITER = `\
You are a senior QA engineer writing short, professional file-level comments.
Output ONLY the comment block — no prose, no explanation, no code.
Match the comment style of the target language (// for Java/TS, # for YAML/shell).
Keep it to 4-6 lines maximum.`;

export const AI_SYSTEM_EXPLAINER = `\
You are a senior QA architect reviewing a test-framework blueprint.
Explain what the blueprint will generate in plain English, suitable for a
developer who has never used this tool before.
Be specific about the chosen framework, language, architecture, and add-ons.
Format your response as a short paragraph followed by a bullet list.
Keep the total under 200 words.`;

// ─── Doc prompts ─────────────────────────────────────────────────────────────

export function readmePrompt(framework: string, language: string, architecture: string, nodes: string[], projectName: string): string {
  return `\
Generate a README.md for a "${projectName}" test automation project.
Framework: ${framework} | Language: ${language} | Architecture pattern: ${architecture}
Active add-ons / nodes: ${nodes.join(', ') || 'none'}

Include:
1. Brief description (2 sentences max)
2. Prerequisites (language runtime, build tool, browser driver)
3. Quick-start (clone → install → run tests — exact commands)
4. Project structure (concise directory tree with one-line explanations)
5. Configuration (key env vars / config file entries)
6. How to run in CI (one GitHub Actions snippet)

Do NOT include a license section.`;
}

export function architecturePrompt(framework: string, language: string, architecture: string, nodes: string[]): string {
  return `\
Write an ARCHITECTURE.md for a ${framework}/${language} test automation framework
using the ${architecture} pattern.
Active nodes / plugins: ${nodes.join(', ') || 'none'}

Sections required:
1. Design decisions (why this architecture was chosen)
2. Layer diagram (ASCII box diagram — keep it simple)
3. Key components (3-5 bullet points)
4. Extension points (how to add new pages / tests / utilities)

Be concise. Under 400 words total.`;
}

export function developerGuidePrompt(framework: string, language: string, nodes: string[]): string {
  return `\
Write a DEVELOPER_GUIDE.md for a ${framework}/${language} test automation project.
Active features: ${nodes.join(', ') || 'none'}

Sections:
1. Adding a new test (step-by-step with a short code snippet)
2. Running a single test / tag
3. Debugging a failing test (3-4 practical tips)
4. Reporting (how to view or generate a report)
5. Common pitfalls

Keep the guide actionable. Under 500 words.`;
}

// ─── File header prompts ──────────────────────────────────────────────────────

export function fileHeaderPrompt(filePath: string, framework: string, language: string, purpose: string): string {
  const ext = filePath.split('.').pop() ?? '';
  const style = ['java', 'ts', 'js', 'tsx'].includes(ext)
    ? 'Java/TypeScript (//-style comments, with a /** */ block)'
    : 'YAML or shell (# style comments)';

  return `\
Write a file-level comment for: ${filePath}
Framework: ${framework} | Language: ${language}
Purpose: ${purpose}
Comment style: ${style}

Rules:
- 4-6 lines
- Describe WHAT the file does and WHY it matters in this framework
- Include "@generated by Qlitz Generator" on the last line
- Output ONLY the comment block — nothing else`;
}

// ─── Blueprint explain prompt ─────────────────────────────────────────────────

export function blueprintExplainPrompt(
  framework: string,
  language: string,
  architecture: string,
  nodes: string[],
  projectName: string,
): string {
  return `\
Explain what will be generated for the "${projectName}" project:
Framework: ${framework} | Language: ${language}
Architecture: ${architecture}
Selected nodes / add-ons: ${nodes.join(', ') || 'none'}

Output: one short paragraph + bullet list of the most important things the developer will get.
Keep it under 200 words. Be specific and practical.`;
}
